SELECT
  (SELECT ID
   FROM CS_CLASS
   WHERE lower(NAME) = 'tag') AS CLASS_ID,
       TAG_ID AS OBJECT_ID
FROM UIMDI02.CSX_OBJECT_TAG
WHERE class_id = %CLASS_ID%
  AND object_id IN (%OBJECT_IDS%)
GROUP BY TAG_ID