 MERGE INTO TAG EXISTING_TAG USING
  (SELECT ? KEY,
            ? NAME, ? DESCRIPTION,
                     ID TAGGROUP
   FROM TAGGROUP
   WHERE TAGGROUP.KEY = ?) NEW_TAG ON (EXISTING_TAG.KEY = NEW_TAG.KEY AND EXISTING_TAG.TAGGROUP = NEW_TAG.TAGGROUP) 
    WHEN NOT matched THEN insert(KEY, NAME, DESCRIPTION, TAGGROUP)
VALUES(NEW_TAG.KEY,
       NEW_TAG.NAME, NEW_TAG.DESCRIPTION,
                    NEW_TAG.TAGGROUP)