SELECT DISTINCT T_BIS_STANDORT_D.PK AS STANDORT_PK,
                rtrim(xmlagg (xmlelement (e, T_BIS_PROBE_B.PK || ',')).extract ('//text()'), ',') PROBEN_PKS,
                T_BIS_PARAMETER_B.PK AS PARAMETER_PK,
                T_BIS_PARAMETER_B.TEXT_TXT PARAMETER_NAME,
                MAX(TO_DATE(T_BIS_PROBE_B.PROBENAHMEDATUM_TXT, 'YYYYMMDD')) AS PROBENAHMEDATUM,
                MIN(T_BIS_MESSWERT_F.WERT_NUM) AS MIN_MESSWERT,
                MAX(T_BIS_MESSWERT_F.WERT_NUM) AS MAX_MESSWERT
FROM T_BIS_MESSWERT_F
INNER JOIN T_BIS_PARAMETER_B ON T_BIS_PARAMETER_B.PK = T_BIS_MESSWERT_F.FK_T_BIS_PARAM_B
AND T_BIS_PARAMETER_B.PK IN (%PARAMETER_PKS%)
--INNER JOIN T_BIS_PARAMGRUPPE_D ON T_BIS_PARAMGRUPPE_D.PK = T_BIS_PARAMETER_B.FK_T_BIS_PARAMGRUPPE_D
--AND T_BIS_PARAMGRUPPE_D.PK IN (%PARAMGROUP%)
INNER JOIN T_BIS_PROBE_B ON T_BIS_PROBE_B.PK = T_BIS_MESSWERT_F.FK_T_BIS_PROBE_B
INNER JOIN T_BIS_STANDORT_D ON T_BIS_STANDORT_D.PK = T_BIS_PROBE_B.FK_T_BIS_STANDORT_D
--WHERE T_BIS_MESSWERT_F.WERT_NUM > 0
GROUP BY T_BIS_STANDORT_D.PK,,
         T_BIS_PARAMETER_B.PK,
         T_BIS_PROBE_B.PROBENAHMEDATUM_TXT,
         T_BIS_PARAMETER_B.TEXT_TXT
ORDER BY T_BIS_STANDORT_D.PK,
         T_BIS_PARAMETER_B.PK
