SELECT DISTINCT %CLASS_ID% AS class_id, BORIS_SITE.ID as id, BORIS_SITE.NAME as name 
FROM BORIS_SITE 
INNER JOIN JT_BORIS_SSV ON JT_BORIS_SSV.BORIS_SITE = BORIS_SITE.ID 
AND BORIS_SITE.ID IN (%OBJECT_IDS%) 
INNER JOIN BORIS_SAMPLE_VALUE ON JT_BORIS_SSV.BORIS_SAMPLE_VALUE = BORIS_SAMPLE_VALUE.ID 
WHERE %MAX_SAMPLE_VALUE_CONDITION%
AND BORIS_SAMPLE_VALUE.MIN_DATE BETWEEN (TO_DATE('%MIN_DATE%', 'YYYYMMDD')-1) AND (TO_DATE('%MAX_DATE%', 'YYYYMMDD')+1)
AND BORIS_SAMPLE_VALUE.MAX_DATE BETWEEN (TO_DATE('%MIN_DATE%', 'YYYYMMDD')-1) AND (TO_DATE('%MAX_DATE%', 'YYYYMMDD')+1)
GROUP BY BORIS_SITE.ID, BORIS_SITE.NAME
--HAVING COUNT (BORIS_SITE.ID) = %NUM_MAX_SAMPLE_VALUE_CONDITIONS% 
--ORDER BY BORIS_SITE.NAME