SELECT TAG.ID,
       TAG.KEY,
       TAG.NAME,
       TAG.DESCRIPTION,
       TAG.TAGGROUP AS TAGGROUPID,
       TAG.TAGGROUP_KEY AS TAGGROUPKEY
FROM TAG
INNER JOIN JT_BORIS_SITE_TAG ON JT_BORIS_SITE_TAG.TAG_ID = TAG.ID
AND JT_BORIS_SITE_TAG.BORIS_SITE_ID = ?
ORDER BY TAG.TAGGROUP_KEY,
         TAG.KEY
