INSERT INTO BORIS_SITE (
    "KEY", 
    "NAME", 
    DESCRIPTION, 
    GEOMETRY, 
    INSTITUTION, 
    LITERATURE, 
    SAMPLES,
    SRC_STANDORT_PK, 
    SRC_CONTENT)
VALUES (?,
        ?,
        ?,
        ?,
        (SELECT ID FROM TAG WHERE KEY = ? AND TAGGROUP_KEY='BORIS.INSTITUT'),
        (SELECT ID FROM TAG WHERE KEY = ? AND TAGGROUP_KEY='BORIS.LITERATUR'),
        (SELECT BORIS_SITE_ID_SEQ.CURRVAL FROM DUAL),
        ?,
        ?)