MERGE INTO JT_BORIS_SITE_SAMPLE_VALUE EXISTING_JT_BRSSV USING
     (SELECT ? BORIS_SITE_ID, ? BORIS_SAMPLE_VALUE_ID FROM DUAL) NEW_JT_BRSSV
 ON (EXISTING_JT_BRSSV.BORIS_SITE_ID = NEW_JT_BRSSV.BORIS_SITE_ID 
     AND EXISTING_JT_BRSSV.BORIS_SAMPLE_VALUE_ID = NEW_JT_BRSSV.BORIS_SAMPLE_VALUE_ID) 
 WHEN NOT matched THEN insert(BORIS_SITE_ID, BORIS_SAMPLE_VALUE_ID)
     VALUES(NEW_JT_BRSSV.BORIS_SITE_ID,
        NEW_JT_BRSSV.BORIS_SAMPLE_VALUE_ID)
