INSERT INTO JT_BORIS_SITE_TAG (BORIS_SITE, TAG) 
    SELECT DISTINCT ? BORIS_SITE, POLLUTANT_GROUP TAG 
        FROM BORIS_SAMPLE_VALUE
        WHERE BORIS_SAMPLE_VALUE.ID IN 
            (SELECT BORIS_SAMPLE_VALUE FROM JT_BORIS_SSV WHERE BORIS_SITE = ?)
    UNION 
    SELECT ? BORIS_SITE, POLLUTANT TAG 
        FROM BORIS_SAMPLE_VALUE
        WHERE BORIS_SAMPLE_VALUE.ID IN 
    (SELECT BORIS_SAMPLE_VALUE FROM JT_BORIS_SSV WHERE BORIS_SITE = ?)

-- MERGE INTO JT_BORIS_SITE_TAG EXISTING_JTBRST USING
--     (SELECT ? BORIS_SITE_ID, ? TAG_ID FROM DUAL) NEW_JTBRST
-- ON (EXISTING_JTBRST.BORIS_SITE_ID = NEW_JTBRST.BORIS_SITE_ID 
--     AND EXISTING_JTBRST.TAG_ID = NEW_JTBRST.TAG_ID) 
-- WHEN NOT matched THEN insert(BORIS_SITE_ID, TAG_ID)
--     VALUES(NEW_JTBRST.BORIS_SITE_ID,
--        NEW_JTBRST.TAG_ID);