INSERT INTO BORIS_SAMPLE_VALUE (
"NAME", 
POLLUTANT, 
POLLUTANT_GROUP, 
MIN_DATE, 
MAX_DATE, 
MIN_VALUE, 
MAX_VALUE, 
SRC_CONTENT)
VALUES( 
    (SELECT NVL(DISPLAY_NAME, PARAMETER_NAME) 
        FROM CSX_MAPPING_BORIS MAPPING WHERE PARAMETER_PK = ? 
        AND POLLUTANT_KEY IS NOT NULL AND ROWNUM = 1),
    (SELECT ID FROM TAG JOIN CSX_MAPPING_BORIS MAPPING ON TAG.KEY = 
        MAPPING.POLLUTANT_KEY AND MAPPING.PARAMETER_PK = ? 
        AND MAPPING.POLLUTANT_KEY IS NOT NULL WHERE ROWNUM = 1),
    (SELECT ID FROM TAGGROUP JOIN CSX_MAPPING_BORIS MAPPING ON TAGGROUP.KEY = 
        MAPPING.POLLUTANTGROUP_KEY AND MAPPING.PARAMETER_PK = ? 
        AND MAPPING.POLLUTANT_KEY IS NOT NULL WHERE ROWNUM = 1),
    ?, 
    ?, 
    ?, 
    ?, 
    ?)