INSERT INTO JT_BORIS_SITE_TAG (BORIS_SITE_ID, TAG_ID) 
    SELECT DISTINCT ? BORIS_SITE_ID, POLLUTANT_GROUP TAG_ID 
        FROM BORIS_SAMPLE_VALUE
        WHERE BORIS_SAMPLE_VALUE.ID IN 
            (SELECT BORIS_SAMPLE_VALUE_ID FROM JT_BORIS_SITE_SAMPLE_VALUE WHERE BORIS_SITE_ID = ?)
    UNION 
    SELECT ? BORIS_SITE_ID, POLLUTANT TAG_ID 
        FROM BORIS_SAMPLE_VALUE
        WHERE BORIS_SAMPLE_VALUE.ID IN (
            SELECT BORIS_SAMPLE_VALUE_ID FROM JT_BORIS_SITE_SAMPLE_VALUE WHERE BORIS_SITE_ID = ?)

-- MERGE INTO JT_BORIS_SITE_TAG EXISTING_JTBRST USING
--     (SELECT ? BORIS_SITE_ID, ? TAG_ID FROM DUAL) NEW_JTBRST
-- ON (EXISTING_JTBRST.BORIS_SITE_ID = NEW_JTBRST.BORIS_SITE_ID 
--     AND EXISTING_JTBRST.TAG_ID = NEW_JTBRST.TAG_ID) 
-- WHEN NOT matched THEN insert(BORIS_SITE_ID, TAG_ID)
--     VALUES(NEW_JTBRST.BORIS_SITE_ID,
--        NEW_JTBRST.TAG_ID);