MERGE INTO JT_BORIS_SSV EXISTING_JT_BRSSV USING
     (SELECT ? BORIS_SITE, ? BORIS_SAMPLE_VALUE FROM DUAL) NEW_JT_BRSSV
 ON (EXISTING_JT_BRSSV.BORIS_SITE = NEW_JT_BRSSV.BORIS_SITE 
     AND EXISTING_JT_BRSSV.BORIS_SAMPLE_VALUE = NEW_JT_BRSSV.BORIS_SAMPLE_VALUE) 
 WHEN NOT matched THEN insert(BORIS_SITE, BORIS_SAMPLE_VALUE)
     VALUES(NEW_JT_BRSSV.BORIS_SITE,
        NEW_JT_BRSSV.BORIS_SAMPLE_VALUE)
