INSERT INTO BORIS_SITE (
    "KEY", 
    "NAME", 
    DESCRIPTION, 
    GEOMETRY, 
    INSTITUTION, 
    LITERATURE, 
    --TAGS, 
    --SAMPLE_VALUES,
    SRC_STANDORT_PK, 
    SRC_CONTENT) 
VALUES( 
    ?,
    ?,
    ?,
    ?, 
    (SELECT ID FROM TAG WHERE KEY = ? AND TAGGROUP_KEY='BORIS.INSTITUT'),  
    (SELECT ID FROM TAG WHERE KEY = ? AND TAGGROUP_KEY='BORIS.LITERATUR'),  
    -- DOES NOT WORK!!!!!!! CURRVAL IS NOT DEFINED, NEXVTAL = ID-- 
    -- BORIS_SITE_ID_SEQ.CURRVAL TAGS, 
    -- BORIS_SITE_ID_SEQ.CURRVAL SAMPLE_VALUES, 
    --(SELECT MAX(ID)+1 FROM BORIS_SITE), 
    --(SELECT MAX(ID)+1 FROM BORIS_SITE), 
    ?, 
    ?)


