-- SELECT PARAMETER_PK,
--        DISPLAY_NAME,
--        PARAMETER_NAME,
--        NVL(DISPLAY_NAME, PARAMETER_NAME) NAME
-- FROM UIMDI02.CSX_MAPPING_BORIS;

INSERT INTO BORIS_SAMPLE_VALUE (
"KEY", 
"NAME", 
POLLUTANT, 
POLLUTANT_GROUP, 
MIN_DATE, 
MAX_DATE, 
MIN_VALUE, 
MAX_VALUE, 
SRC_CONTENT)
SELECT 'BLAH' "KEY", 
    NVL(DISPLAY_NAME, PARAMETER_NAME) "NAME",
    (SELECT ID FROM TAG WHERE KEY = MAPPING.POLLUTANT_KEY AND ROWNUM = 1) POLLUTANT,
    (SELECT ID FROM TAGGROUP WHERE KEY = MAPPING.POLLUTANTGROUP_KEY AND ROWNUM = 1) POLLUTANT_GROUP,
    TO_DATE('20120201', 'YYYYMMDD') MIN_DATE, 
    TO_DATE('20150914', 'YYYYMMDD') MAX_DATE, 
    27.0 MIN_VALUE, 
    115.698 MAX_VALUE, 
    'SRC_CONTENT' SRC_CONTENT
    FROM CSX_MAPPING_BORIS MAPPING
    WHERE PARAMETER_PK = 'B432' AND POLLUTANT_KEY IS NOT NULL AND ROWNUM = 1 


     --SELECT ID FROM TAG WHERE KEY = 'Fe' AND ROWNUM = 1;
    --SELECT ID FROM TAGGOUP WHERE KEY = 'Fe' AND ROWNUM = 1;
