BEGIN

MERGE INTO TAGGROUP EXISTING_TAGGROUP USING
  (SELECT 'BORIS.LITERATUR' KEY, 'Literatur' NAME, 'Literatur' DESCRIPTION
    FROM DUAL) NEW_TAGGROUP ON (EXISTING_TAGGROUP.KEY = NEW_TAGGROUP.KEY) 
WHEN NOT matched THEN insert(KEY, NAME, DESCRIPTION)
VALUES(NEW_TAGGROUP.KEY,
       NEW_TAGGROUP.NAME, NEW_TAGGROUP.DESCRIPTION);

MERGE INTO TAGGROUP EXISTING_TAGGROUP USING
  (SELECT 'BORIS.INSTITUT' KEY, 'Institut' NAME, 'Institut' DESCRIPTION
    FROM DUAL) NEW_TAGGROUP ON (EXISTING_TAGGROUP.KEY = NEW_TAGGROUP.KEY) 
WHEN NOT matched THEN insert(KEY, NAME, DESCRIPTION)
VALUES(NEW_TAGGROUP.KEY,
       NEW_TAGGROUP.NAME, NEW_TAGGROUP.DESCRIPTION);

END;