INSERT INTO BORIS_SAMPLE_VALUE (
NAME, 
POLLUTANT, 
POLLUTANT_GROUP, 
MIN_DATE, 
MAX_DATE, 
MIN_VALUE, 
MAX_VALUE, 
SRC_CONTENT)
VALUES(
:NAME, 
(SELECT ID FROM TAG WHERE TAG.KEY = :POLLUTANT AND ROWNUM = 1), 
(SELECT ID FROM TAG WHERE TAG.KEY = :POLLUTANT_GROUP AND ROWNUM = 1),
:MIN_DATE, 
:MAX_DATE, 
:MIN_VALUE, 
:MAX_VALUE, 
:SRC_CONTENT)