SELECT DISTINCT PARAMETER_PK,
                NVL(DISPLAY_NAME, PARAMETER_NAME) DISPLAY_NAME,
                POLLUTANT_KEY,
                POLLUTANTGROUP_KEY
FROM CSX_MAPPING_BORIS
WHERE POLLUTANT_KEY IS NOT NULL