SELECT DISTINCT PARAMETER_PK,
                NVL(DISPLAY_NAME, PARAMETER_NAME) DISPLAY_NAME,
                POLLUTANT_KEY AS POLLUTANT_TAG_KEY,
                POLLUTANTGROUP_KEY POLLUTANTGROUP_TAG_KEY,
                POLLUTANT_TAG.ID AS POLLUTANT_TAG_ID,
                POLLUTANTGROUP_TAG.ID AS POLLUTANTGROUP_TAG_ID,
                POLLUTANT_TAG.NAME AS POLLUTANT_TAG_NAME,
                POLLUTANTGROUP_TAG.NAME AS POLLUTANTGROUP_TAG_NAME
FROM CSX_MAPPING_BORIS
INNER JOIN TAG POLLUTANT_TAG ON POLLUTANT_TAG.KEY = POLLUTANT_KEY 
    AND POLLUTANT_TAG.TAGGROUP_KEY = 'POLLUTANT'
INNER JOIN TAG POLLUTANTGROUP_TAG ON POLLUTANTGROUP_TAG.KEY = POLLUTANTGROUP_KEY
    AND POLLUTANTGROUP_TAG.TAGGROUP_KEY = 'POLLUTANTGROUP'
WHERE POLLUTANT_KEY IS NOT NULL
ORDER BY PARAMETER_PK