SELECT DISTINCT T_BIS_PROBE_B.FK_T_BIS_STANDORT_D AS STANDORT_PK,
                T_BIS_PROBE_B.PK AS PROBE_PK,
                TO_DATE(T_BIS_PROBE_B.PROBENAHMEDATUM_TXT, 'YYYYMMDD') AS PROBENAHMEDATUM,
                T_BIS_PROBE_B.PROBEVON_NUM AS PROBEVON,
                T_BIS_PROBE_B.PROBEBIS_NUM AS PROBEBIS,
                %PARAMETER_DECODE_FUNCTIONS%
FROM T_BIS_MESSWERT_F MESSWERT
INNER JOIN T_BIS_PARAMETER_B PARAMETER ON PARAMETER.PK = MESSWERT.FK_T_BIS_PARAM_B 
/*INNER JOIN T_BIS_PARAMGRUPPE_D ON T_BIS_PARAMGRUPPE_D.PK = T_BIS_PARAMETER_B.FK_T_BIS_PARAMGRUPPE_D
AND T_BIS_PARAMGRUPPE_D.PK IN ('B30000',
                               'B40000',
                               'B40100',
                               'B40200',
                               'B40300',
                               'B40400',
                               'B40500',
                               'B40600')*/
AND PARAMETER.PK IN (%PARAMETER_PKS%)
INNER JOIN T_BIS_PROBE_B ON T_BIS_PROBE_B.PK = MESSWERT.FK_T_BIS_PROBE_B
AND T_BIS_PROBE_B.FK_T_BIS_STANDORT_D IN (%STANDORT_PKS%)
WHERE TO_DATE(T_BIS_PROBE_B.PROBENAHMEDATUM_TXT, 'YYYYMMDD') 
    BETWEEN TO_DATE('%FROMDATE-YYYY-MM-DD%', 'YYYY-MM-DD') 
    AND TO_DATE('%TODATE-YYYY-MM-DD%', 'YYYY-MM-DD')
GROUP BY T_BIS_PROBE_B.FK_T_BIS_STANDORT_D,
         T_BIS_PROBE_B.PK,
         PROBENAHMEDATUM_TXT,
         T_BIS_PROBE_B.PROBEVON_NUM,
         T_BIS_PROBE_B.PROBEBIS_NUM
ORDER BY T_BIS_PROBE_B.FK_T_BIS_STANDORT_D,
         T_BIS_PROBE_B.PK
