 MERGE INTO TAG EXISTING_TAG USING
  (SELECT ? KEY, ? NAME,
                   ? DESCRIPTION,
                     TAGGROUP.ID TAGGROUP,
                     TAGGROUP.KEY TAGGROUP_KEY
   FROM TAGGROUP
   WHERE TAGGROUP.KEY = ?) NEW_TAG ON (EXISTING_TAG.KEY = NEW_TAG.KEY
   AND EXISTING_TAG.TAGGROUP = NEW_TAG.TAGGROUP) 
    WHEN NOT matched THEN insert(KEY, NAME, DESCRIPTION, TAGGROUP, TAGGROUP_KEY)
    VALUES(NEW_TAG.KEY, NEW_TAG.NAME,
                        NEW_TAG.DESCRIPTION,
                        NEW_TAG.TAGGROUP,
                        NEW_TAG.TAGGROUP_KEY)