MAX(DECODE(MOSS_SAMPLE_VALUE.POLLUTANT, (SELECT POLLUTANT_TAG.ID FROM CSX_MAPPING_MOSS
          INNER JOIN TAG POLLUTANT_TAG ON POLLUTANT_TAG.KEY = CSX_MAPPING_MOSS.POLLUTANT_KEY 
          WHERE CSX_MAPPING_MOSS.PARAMETER_PK = '%PARAMETER_PK%'), MOSS_SAMPLE_VALUE."VALUE")) AS "%PARAMETER_NAME%"