SELECT SAMPLE_ID,
       LAB_NO,
       MOSS_TYPE.TYPE AS TYPE,
       GEOM.GEO_FIELD.sdo_point.x AS XCOORDINATE,
       GEOM.GEO_FIELD.sdo_point.y AS YCOORDINATE,
       TO_DATE('2010-10-21', 'YYYY-MM-DD') AS SAMPLE_DATE,
       %MOSS_DECODE_STATEMENTS%
FROM MOSS
INNER JOIN MOSS_TYPE ON MOSS_TYPE.ID = MOSS.MOSS_TYPE
INNER JOIN GEOM ON GEOM.ID = MOSS.GEOMETRY
WHERE MOSS.ID IN (%MOSS_IDS%)
ORDER BY MOSS.ID