SELECT
    MOSS_STATION.*,
    GEOM.GEO_FIELD.sdo_point.x AS XCOORDINATE,
    GEOM.GEO_FIELD.sdo_point.y AS YCOORDINATE
FROM(SELECT MOSS.SRC_SAMPLE_ID AS SAMPLE_ID,
       TYPE_TAG.NAME AS MOSS_TYPE,
       MOSS_SAMPLE_VALUE.SAMPLE_DATE,
       %MOSS_DECODE_STATEMENTS%
FROM MOSS
INNER JOIN MOSS_SAMPLE_VALUE ON MOSS_SAMPLE_VALUE.STATION = MOSS.ID
INNER JOIN TAG TYPE_TAG ON TYPE_TAG.ID = MOSS.MOSS_TYPE
WHERE MOSS.ID IN (%MOSS_IDS%)
AND MOSS_SAMPLE_VALUE.POLLUTANT IN (SELECT TAG.ID FROM CSX_MAPPING_MOSS
JOIN TAG ON TAG.KEY = CSX_MAPPING_MOSS.POLLUTANT_KEY 
WHERE CSX_MAPPING_MOSS.PARAMETER_PK IN (%PARAMETER_PKS%))
GROUP BY MOSS.SRC_SAMPLE_ID, 
    TYPE_TAG.NAME,
    MOSS.GEOMETRY,
    MOSS_SAMPLE_VALUE.SAMPLE_DATE
ORDER BY MOSS.SRC_SAMPLE_ID, MOSS_SAMPLE_VALUE.SAMPLE_DATE)  MOSS_STATION
INNER JOIN GEOM ON GEOM.ID = (SELECT GEOMETRY FROM MOSS WHERE MOSS.SRC_SAMPLE_ID = MOSS_STATION.SAMPLE_ID)