INSERT INTO JT_MOSS_TAG (MOSS, TAG) 
    SELECT DISTINCT :STATION_ID MOSS, POLLUTANT_GROUP TAG 
        FROM MOSS_SAMPLE_VALUE
        WHERE MOSS_SAMPLE_VALUE.STATION = :STATION_ID
        GROUP BY POLLUTANT_GROUP 
    UNION 
    SELECT DISTINCT :STATION_ID MOSS, POLLUTANT TAG 
        FROM MOSS_SAMPLE_VALUE
        WHERE MOSS_SAMPLE_VALUE.STATION = :STATION_ID
        GROUP BY POLLUTANT