ALTER SESSION SET ddl_lock_timeout=360;
ALTER TABLE MOSS DISABLE CONSTRAINT MOSS_FK1;
DELETE FROM GEOM WHERE ID IN (SELECT MOSS.GEOMETRY FROM MOSS);
DELETE FROM TAG WHERE ID IN (SELECT DISTINCT MOSS.MOSS_TYPE FROM MOSS);
TRUNCATE TABLE MOSS;
TRUNCATE TABLE MOSS_SAMPLE_VALUE;
ALTER TABLE MOSS ENABLE CONSTRAINT MOSS_FK1;