SELECT DISTINCT T_BIS_PROBE_B.FK_T_BIS_STANDORT_D AS STANDORT_PK,
                T_BIS_STANDORT_D.RECHTSWERT_NUM AS RECHTSWERT,
                T_BIS_STANDORT_D.HOCHWERT_NUM AS HOCHWERT,
                T_BIS_PROBE_B.PK AS PROBE_PK,
                TO_DATE(T_BIS_PROBE_B.PROBENAHMEDATUM_TXT, 'YYYYMMDD') AS PROBENAHMEDATUM,
                T_BIS_PROBE_B.PROBEVON_NUM AS PROBEVON,
                T_BIS_PROBE_B.PROBEBIS_NUM AS PROBEBIS,
                %MESSWERT_DECODE_STATEMENTS%
                --MAX(DECODE(MESSWERT.FK_T_BIS_PARAM_B, 'BCU1', MESSWERT.WERT_NUM)) AS BCU1,
                --MAX(DECODE(MESSWERT.FK_T_BIS_PARAM_B, 'BZN1', MESSWERT.WERT_NUM)) AS BZN1,
                --MAX(DECODE(MESSWERT.FK_T_BIS_PARAM_B, 'BPB1', MESSWERT.WERT_NUM)) AS BPB1
FROM T_BIS_MESSWERT_F MESSWERT
INNER JOIN T_BIS_PARAMETER_B PARAMETER ON PARAMETER.PK = MESSWERT.FK_T_BIS_PARAM_B
--AND PARAMETER.PK IN ('BCU1','BZN1','BPB1')
AND PARAMETER.PK IN (%MESSWERT_PARAMETER_PKS%)
INNER JOIN T_BIS_PROBE_B ON T_BIS_PROBE_B.PK = MESSWERT.FK_T_BIS_PROBE_B --INNER JOIN T_BIS_STANDORT_D ON T_BIS_STANDORT_D.PK = T_BIS_PROBE_B.FK_T_BIS_STANDORT_D
--AND T_BIS_PROBE_B.FK_T_BIS_STANDORT_D IN ('1000066', '1000067')
AND T_BIS_PROBE_B.FK_T_BIS_STANDORT_D IN (%STANDORT_PKS%)
--WHERE TO_DATE(T_BIS_PROBE_B.PROBENAHMEDATUM_TXT, 'YYYYMMDD') BETWEEN
    --TO_DATE('19981020', 'YYYYMMDD') AND
    --TO_DATE('19981020', 'YYYYMMDD')
--    %MIN_DATE% AND
--    %MAX_DATE%
INNER JOIN T_BIS_STANDORT_D ON T_BIS_STANDORT_D.PK = T_BIS_PROBE_B.FK_T_BIS_STANDORT_D
GROUP BY T_BIS_PROBE_B.FK_T_BIS_STANDORT_D,
         T_BIS_STANDORT_D.RECHTSWERT_NUM,
         T_BIS_STANDORT_D.HOCHWERT_NUM,
         T_BIS_PROBE_B.PK,
         PROBENAHMEDATUM_TXT,
         /*T_BIS_PROBE_B.PROBENAHMEDATUM_TXT,*/
         T_BIS_PROBE_B.PROBEVON_NUM,
         T_BIS_PROBE_B.PROBEBIS_NUM --, T_BIS_MESSWERT_F.FK_T_BIS_PARAM_B, T_BIS_MESSWERT_F.WERT_NUM
--HAVING COUNT(T_BIS_PARAMETER_B.PK) = 3
--HAVING COUNT(distinct PROBENAHMEDATUM_TXT) > 1
ORDER BY T_BIS_PROBE_B.FK_T_BIS_STANDORT_D,
         T_BIS_PROBE_B.PK