CREATE TABLE CSX_MAPPING_WAGW ( PARAMETER_PK VARCHAR2(32),
PARAMETER_NAME VARCHAR2(128) NOT NULL,
PARAMETER_GROUP_PK VARCHAR2(32),
PARAMETER_GROUP_NAME VARCHAR2(128),
POLLUTANT_KEY VARCHAR2(64),
POLLUTANTGROUP_KEY VARCHAR2(64),
DISPLAY_NAME VARCHAR2(256),
UNIT VARCHAR2(64),
AGGREGATION_PK VARCHAR2(32),
AGGREGATION_CONVERSION VARCHAR2(128));

CREATE INDEX CSX_MAPPING_GW_IDXV1 ON CSX_MAPPING_WAGW 
  (
    PARAMETER_PK ASC
  );
  
CREATE INDEX CSX_MAPPING_GW_IDXV2 ON CSX_MAPPING_WAGW 
  (
    AGGREGATION_PK ASC
  );
  
CREATE INDEX CSX_MAPPING_GW_IDXV3 ON CSX_MAPPING_WAGW 
  (
    POLLUTANT_KEY ASC
  );
  
CREATE INDEX CSX_MAPPING_GW_IDXV4 ON CSX_MAPPING_WAGW 
  (
    POLLUTANTGROUP_KEY ASC
  );
  

ALTER TABLE CSX_MAPPING_WAGW ADD CONSTRAINT CSX_MAPPING_WAGW_PK PRIMARY KEY ( PARAMETER_PK );

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G539', '1-METHYL-3-NITROGUANIDIN µg/l', '', '', '', '', '1-METHYL-3-NITROGUANIDIN µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G186', '1,1-DICHLORETHEN µg/l', '', '', '', '', '1,1-DICHLORETHEN µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G177', '1,1,1-TRICHLORETHAN µg/l', '', '', 'Trichlorethan', 'KWS', '1,1,1-TRICHLORETHAN µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G187', '1,2-DICHLORETHAN µg/l', '', '', 'EDC', 'PEST', '1,2-DICHLORETHAN µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G331', '1,2-DICHLORETHEN (CIS) µg/l', '', '', '', '', '1,2-DICHLORETHEN (CIS) µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G330', '1,2-DICHLORETHEN (TRANS) µg/l', '', '', '', '', '1,2-DICHLORETHEN (TRANS) µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G326', '1,3-DICHLORBENZOL µg/l', '', '', '', '', '1,3-DICHLORBENZOL µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G327', '1,4-DICHLORBENZOL µg/l', '', '', '', '', '1,4-DICHLORBENZOL µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G461', '2-AMINO-4-METHOXY-6-METHYL-1,3,5-TRIAZIN µg/l', '', '', '', '', '2-AMINO-4-METHOXY-6-METHYL-1,3,5-TRIAZIN µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G535', '2-HYDROXYATRAZIN µg/l', '', '', '', '', '2-HYDROXYATRAZIN µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G197', '2,4-D µg/l', '', '', '', '', '2,4-D µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G217', '2,4,5-T µg/l', '', '', '', '', '2,4,5-T µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G378', '2,6-DICHLORBENZAMID µg/l', '', '', '', '', '2,6-DICHLORBENZAMID µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G470', '3-AMINOPHENOL µg/l', '', '', '', '', '3-AMINOPHENOL µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G469', '3,5-DIBROM-4-HYDROXYBENZOESÄURE µg/l', '', '', '', '', '3,5-DIBROM-4-HYDROXYBENZOESÄURE µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G468', '3,5,6-TRICHLOR-2-PYRIDINOL (TCP) µg/l', '', '', '', '', '3,5,6-TRICHLOR-2-PYRIDINOL (TCP) µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G109', 'ABSTICH m', '', '', '', '', 'ABSTICH m', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G198', 'ALACHLOR µg/l', '', '', 'Alachlor', 'PEST', 'ALACHLOR µg/l', 'G198', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G478', 'ALACHLOR-SULFONSÄURE µg/l', '', '', 'Alachlor', 'PEST', 'ALACHLOR-SULFONSÄURE µg/l', 'G198', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G266', 'ALDRIN u. DIELDRIN µg/l', '', '', 'Aldrin', 'PEST', 'ALDRIN u. DIELDRIN µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G128', 'ALKALI M-WERT mmol/l', '', '', '', '', 'ALKALI M-WERT mmol/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G146', 'ALUMINIUM mg/l', '', '', 'Al', 'MET', 'ALUMINIUM mg/l', 'G146', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G425', 'ALUMINIUM µg/l', '', '', 'Al', 'MET', 'ALUMINIUM µg/l', 'G146', '$messwert / 1000.0');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G152', 'AMMONIUM mg/l', '', '', '', '', 'AMMONIUM mg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G348', 'AMPA µg/l', '', '', '', '', 'AMPA µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G172', 'AOX µg/l', '', '', '', '', 'AOX µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G150', 'ARSEN mg/l', '', '', 'As', 'MET', 'ARSEN mg/l', 'G150', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G429', 'ARSEN µg/l', '', '', 'As', 'MET', 'ARSEN µg/l', 'G150', '$messwert / 1000.0');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G192', 'ATRAZIN µg/l', '', '', 'Atrazin', 'PEST', 'ATRAZIN µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G482', 'AZOXYSTROBIN µg/l', '', '', '', '', 'AZOXYSTROBIN µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G200', 'BENTAZON µg/l', '', '', '', '', 'BENTAZON µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G147', 'BLEI mg/l', '', '', 'Pb', 'MET', 'BLEI mg/l', 'G147', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G426', 'BLEI µg/l', '', '', 'Pb', 'MET', 'BLEI µg/l', 'G147', '$messwert / 1000.0');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G124', 'BLEIBENDE HAERTE °dH', '', '', '', '', 'BLEIBENDE HAERTE °dH', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G151', 'BOR mg/l', '', '', '', '', 'BOR mg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G320', 'BROMACIL µg/l', '', '', '', '', 'BROMACIL µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G182', 'BROMDICHLORMETHAN µg/l', '', '', '', '', 'BROMDICHLORMETHAN µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G243', 'BUTURON µg/l', '', '', '', '', 'BUTURON µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G140', 'CADMIUM mg/l', '', '', 'Cd', 'MET', 'CADMIUM mg/l', 'G140', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G421', 'CADMIUM µg/l', '', '', 'Cd', 'MET', 'CADMIUM µg/l', 'G140', '$messwert / 1000.0');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G134', 'CALCIUM mg/l', '', '', 'Ca', 'DNM', 'CALCIUM mg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G286', 'CHLORBROMURON µg/l', '', '', '', '', 'CHLORBROMURON µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G267', 'CHLORDAN (Summe Isomeren) µg/l', '', '', 'Chlordan', 'PEST', 'CHLORDAN (Summe Isomeren) µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G155', 'CHLORID mg/l', '', '', 'Clr', 'SOSS', 'CHLORID mg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G400', 'Chloridazon µg/l', '', '', '', '', 'Chloridazon µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G180', 'CHLOROFORM (Trichlormethan) µg/l', '', '', '', '', 'CHLOROFORM (Trichlormethan) µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G540', 'CHLOROTHALONIL-SULFONSÄURE µg/l', '', '', '', '', 'CHLOROTHALONIL-SULFONSÄURE µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G170', 'CHLORPHENOLE µg/l', '', '', '', '', 'CHLORPHENOLE µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G244', 'CHLORTOLURON µg/l', '', '', '', '', 'CHLORTOLURON µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G148', 'CHROM-GESAMT mg/l', '', '', 'Cr', 'MET', 'CHROM-GESAMT mg/l', 'G148', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G427', 'CHROM-GESAMT µg/l', '', '', 'Cr', 'MET', 'CHROM-GESAMT µg/l', 'G148', '$messwert / 1000.0');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G364', 'CLOMAZON µg/l', '', '', '', '', 'CLOMAZON µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G336', 'CSB (Cr) mg/l', '', '', '', '', 'CSB (Cr) mg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G218', 'CYANAZIN µg/l', '', '', '', '', 'CYANAZIN µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G486', 'CYPM µg/l', '', '', '', '', 'CYPM µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G245', 'DDE (und Isomere) µg/l', '', '', '', '', 'DDE (und Isomere) µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G246', 'DDT (und Isomere) µg/l', '', '', 'DDT', 'PEST', 'DDT (und Isomere) µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G353', 'DELTAMETRIN µg/l', '', '', '', '', 'DELTAMETRIN µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G386', 'Desethyl-Desisopropylatrazin µg/l', '', '', '', '', 'Desethyl-Desisopropylatrazin µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G193', 'DESETHYLATRAZIN µg/l', '', '', '', '', 'DESETHYLATRAZIN µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G379', 'DESETHYLTERBUTHYLAZIN µg/l', '', '', '', '', 'DESETHYLTERBUTHYLAZIN µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G194', 'DESISOPROPYLATRAZIN µg/l', '', '', '', '', 'DESISOPROPYLATRAZIN µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G401', 'Desphenyl-Chloridazon µg/l', '', '', '', '', 'Desphenyl-Chloridazon µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G227', 'DEUTERIUM d 0/00', '', '', '', '', 'DEUTERIUM d 0/00', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G532', 'DIAZINON µg/l', '', '', '', '', 'DIAZINON µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G183', 'DIBROMCHLORMETHAN µg/l', '', '', '', '', 'DIBROMCHLORMETHAN µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G229', 'DICAMBA µg/l', '', '', '', '', 'DICAMBA µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G316', 'DICHLOBENIL µg/l', '', '', '', '', 'DICHLOBENIL µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G185', 'DICHLORMETHAN µg/l', '', '', '', '', 'DICHLORMETHAN µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G196', 'DICHLORPROP µg/l', '', '', '', '', 'DICHLORPROP µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G494', 'DIMETHACHLOR-SULFONSÄURE µg/l', '', '', '', '', 'DIMETHACHLOR-SULFONSÄURE µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G358', 'DIMETHENAMID µg/l', '', '', '', '', 'DIMETHENAMID µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G541', 'DIMETHENAMID-SULFONSÄURE µg/l', '', '', '', '', 'DIMETHENAMID-SULFONSÄURE µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G247', 'DINOSEB µg/l', '', '', '', '', 'DINOSEB µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G248', 'DINOSEB-ACETAT µg/l', '', '', '', '', 'DINOSEB-ACETAT µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G249', 'DIURON µg/l', '', '', 'Diuron', 'PEST', 'DIURON µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G164', 'DOC mg/l', '', '', '', '', 'DOC mg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G291', 'EISEN GESAMT mg/l', '', '', 'Fe', 'MET', 'EISEN GESAMT mg/l', 'G138', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G138', 'EISEN mg/l', '', '', 'Fe', 'MET', 'EISEN mg/l', 'G138', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G366', 'ELEKTR. LEITF. (bei 20°C) µS/cm', '', '', '', '', 'ELEKTR. LEITF. (bei 20°C) µS/cm', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G117', 'ELEKTR. LEITF. (bei 25°C) µS/cm', '', '', '', '', 'ELEKTR. LEITF. (bei 25°C) µS/cm', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G296', 'ENDRIN µg/l', '', '', 'Endrin', 'PEST', 'ENDRIN µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G441', 'Erythromycin µg/l', '', '', '', '', 'Erythromycin µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G395', 'Ethofumesate µg/l', '', '', '', '', 'Ethofumesate µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G113', 'FAERBUNG', '', '', '', '', 'FAERBUNG', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G359', 'FLUFENACET µg/l', '', '', '', '', 'FLUFENACET µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G499', 'FLUFENACET-SULFONSÄURE µg/l', '', '', '', '', 'FLUFENACET-SULFONSÄURE µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G367', 'FLUROXYPYR µg/l', '', '', '', '', 'FLUROXYPYR µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G215', 'FÖRDERSTROM BEI PN l/s', '', '', '', '', 'FÖRDERSTROM BEI PN l/s', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G325', 'GESAMTFÖRDERVOLUMEN BEI PN l', '', '', '', '', 'GESAMTFÖRDERVOLUMEN BEI PN l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G122', 'GESAMTHAERTE °dH', '', '', '', '', 'GESAMTHAERTE °dH', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G339', 'GLYPHOSAT µg/l', '', '', '', '', 'GLYPHOSAT µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G110', 'GRUNDWASSERSPIEGEL m ü.A.', '', '', '', '', 'GRUNDWASSERSPIEGEL m ü.A.', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G268', 'HEPTACHLOR µg/l', '', '', 'Heptachlor', 'PEST', 'HEPTACHLOR µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G269', 'HEXACHLORBENZOL µg/l', '', '', 'HCB', 'PEST', 'HEXACHLORBENZOL µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G297', 'HEXACHLORBUTADIEN µg/l', '', '', '', '', 'HEXACHLORBUTADIEN µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G315', 'HEXAZINON µg/l', '', '', '', '', 'HEXAZINON µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G157', 'HYDROGENK. mg/l', '', '', '', '', 'HYDROGENK. mg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G534', 'IMIDACLOPRID µg/l', '', '', '', '', 'IMIDACLOPRID µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G251', 'ISOPROTURON µg/l', '', '', '', '', 'ISOPROTURON µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G137', 'KALIUM mg/l', '', '', 'K', 'DNM', 'KALIUM mg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G123', 'KARBONATHAERTE °dH', '', '', '', '', 'KARBONATHAERTE °dH', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G160', 'KIESELSAEURE mg/l', '', '', '', '', 'KIESELSAEURE mg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G163', 'KMnO4-VERBR. mg/l', '', '', '', '', 'KMnO4-VERBR. mg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G332', 'KOHLENSTOFF-13 %o (REL. ZU PDB)', '', '', '', '', 'KOHLENSTOFF-13 %o (REL. ZU PDB)', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G333', 'KOHLENSTOFF-14 Bq/l', '', '', '', '', 'KOHLENSTOFF-14 Bq/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G145', 'KUPFER mg/l', '', '', 'Cu', 'MET', 'KUPFER mg/l', 'G145', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G424', 'KUPFER µg/l', '', '', 'Cu', 'MET', 'KUPFER µg/l', 'G145', '$messwert / 1000.0');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G202', 'LINDAN µg/l', '', '', 'Lindan', 'PEST', 'LINDAN µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G252', 'LINURON µg/l', '', '', '', '', 'LINURON µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G135', 'MAGNESIUM mg/l', '', '', 'Mg', 'DNM', 'MAGNESIUM mg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G292', 'MANGAN GESAMT mg/l', '', '', 'Mn', 'MET', 'MANGAN GESAMT mg/l', 'G139', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G139', 'MANGAN mg/l', '', '', 'Mn', 'MET', 'MANGAN mg/l', 'G139', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G204', 'MCPA µg/l', '', '', '', '', 'MCPA µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G241', 'MCPB µg/l', '', '', '', '', 'MCPB µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G205', 'MCPP µg/l', '', '', '', '', 'MCPP µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G317', 'METALAXYL µg/l', '', '', '', '', 'METALAXYL µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G361', 'METAMITRON µg/l', '', '', '', '', 'METAMITRON µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G504', 'METAMITRON-DESAMINO µg/l', '', '', '', '', 'METAMITRON-DESAMINO µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G253', 'METAZACHLOR µg/l', '', '', '', '', 'METAZACHLOR µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G505', 'METAZACHLOR-SÄURE µg/l', '', '', '', '', 'METAZACHLOR-SÄURE µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G506', 'METAZACHLOR-SULFONSÄURE µg/l', '', '', '', '', 'METAZACHLOR-SULFONSÄURE µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G254', 'METHOXYCHLOR µg/l', '', '', '', '', 'METHOXYCHLOR µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G402', 'Methyldesphenylchloridazon µg/l', '', '', '', '', 'Methyldesphenylchloridazon µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G255', 'METOBROMURON µg/l', '', '', '', '', 'METOBROMURON µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G216', 'METOLACHLOR µg/l', '', '', '', '', 'METOLACHLOR µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G511', 'METOLACHLOR-SÄURE µg/l', '', '', '', '', 'METOLACHLOR-SÄURE µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G510', 'METOLACHLOR-SULFONSÄURE µg/l', '', '', '', '', 'METOLACHLOR-SULFONSÄURE µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G256', 'METOXURON µg/l', '', '', '', '', 'METOXURON µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G397', 'Metribuzin µg/l', '', '', '', '', 'Metribuzin µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G512', 'METRIBUZIN-DESAMINO µg/l', '', '', '', '', 'METRIBUZIN-DESAMINO µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G545', 'MOLYBDÄN µg/l', '', '', '', '', 'MOLYBDÄN µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G257', 'MONOLINURON µg/l', '', '', '', '', 'MONOLINURON µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G258', 'MONURON µg/l', '', '', '', '', 'MONURON µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G328', 'MTBE µg/l', '', '', '', '', 'MTBE µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G383', 'N,N-DIMETHYLSULFAMID µg/l', '', '', '', '', 'N,N-DIMETHYLSULFAMID µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G136', 'NATRIUM mg/l', '', '', 'Na', 'DNM', 'NATRIUM mg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G259', 'NEBURON µg/l', '', '', '', '', 'NEBURON µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G149', 'NICKEL mg/l', '', '', 'Ni', 'MET', 'NICKEL mg/l', 'G149', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G428', 'NICKEL µg/l', '', '', 'Ni', 'MET', 'NICKEL µg/l', 'G149', '$messwert / 1000.0');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G154', 'NITRAT mg/l', '', '', '', '', 'NITRAT mg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G153', 'NITRIT mg/l', '', '', '', '', 'NITRIT mg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G538', 'NITROGUANIDIN µg/l', '', '', '', '', 'NITROGUANIDIN µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G159', 'ORTHOPHOSPHAT mg/l', '', '', '', '', 'ORTHOPHOSPHAT mg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G543', 'PETHOXAMID-SULFONSÄURE µg/l', '', '', '', '', 'PETHOXAMID-SULFONSÄURE µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G118', 'PH-WERT', '', '', '', '', 'PH-WERT', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G201', 'PIRIMICARB µg/l', '', '', '', '', 'PIRIMICARB µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G173', 'POX µg/l', '', '', '', '', 'POX µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G219', 'PROMETRYN µg/l', '', '', '', '', 'PROMETRYN µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G220', 'PROPAZIN µg/l', '', '', '', '', 'PROPAZIN µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G466', 'PROPAZIN-2-HYDROXY µg/l', '', '', '', '', 'PROPAZIN-2-HYDROXY µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G394', 'Propiconazol µg/l', '', '', '', '', 'Propiconazol µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G199', 'PYRIDAT µg/l (als CL9673)', '', '', '', '', 'PYRIDAT µg/l (als CL9673)', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G141', 'QUECKSILBER mg/l', '', '', 'Hg', 'MET', 'QUECKSILBER mg/l', 'G141', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G422', 'QUECKSILBER µg/l', '', '', 'Hg', 'MET', 'QUECKSILBER µg/l', 'G141', '$messwert / 1000.0');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G324', 'RADIUM-226 Bq/l', '', '', '', '', 'RADIUM-226 Bq/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G285', 'RADON-222 Bq/l', '', '', '', '', 'RADON-222 Bq/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G387', 's-Metolachlor µg/l', '', '', '', '', 's-Metolachlor µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G523', 'SACCHARIN µg/l', '', '', '', '', 'SACCHARIN µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G228', 'SAUERSTOFF 18 d 0/00', '', '', '', '', 'SAUERSTOFF 18 d 0/00', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G119', 'SAUERSTOFFGEHALT mg/l', '', '', '', '', 'SAUERSTOFFGEHALT mg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G120', 'SAUERSTOFFSAETTIGUNG %', '', '', '', '', 'SAUERSTOFFSAETTIGUNG %', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G242', 'SEBUTYLAZIN µg/l', '', '', '', '', 'SEBUTYLAZIN µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G195', 'SIMAZIN µg/l', '', '', 'Simazin', 'PEST', 'SIMAZIN µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G156', 'SULFAT mg/l', '', '', '', '', 'SULFAT mg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G221', 'TERBUTHYLAZIN µg/l', '', '', '', '', 'TERBUTHYLAZIN µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G467', 'TERBUTHYLAZIN-2-HYDROXY µg/l', '', '', '', '', 'TERBUTHYLAZIN-2-HYDROXY µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G465', 'TERBUTHYLAZIN-2-HYDROXY-DESETHYL µg/l', '', '', '', '', 'TERBUTHYLAZIN-2-HYDROXY-DESETHYL µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G263', 'TERBUTRYN µg/l', '', '', '', '', 'TERBUTRYN µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G175', 'TETRACHLORETHEN µg/l', '', '', '', '', 'TETRACHLORETHEN µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G179', 'TETRACHLORMETHAN µg/l', '', '', '', '', 'TETRACHLORMETHAN µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G525', 'THIACLOPRID AMID µg/l', '', '', '', '', 'THIACLOPRID AMID µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G390', 'Thiamethoxam µg/l', '', '', '', '', 'Thiamethoxam µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G181', 'TRIBROMMETHAN µg/l', '', '', '', '', 'TRIBROMMETHAN µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G176', 'TRICHLORETHEN µg/l', '', '', '', '', 'TRICHLORETHEN µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G403', 'Triclopyr µg/l', '', '', '', '', 'Triclopyr µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G226', 'TRITIUM TE', '', '', 'METPlus', 'MET', 'TRITIUM TE', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G433', 'URAN µg/l', '', '', 'METPlus', 'MET', 'URAN µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G544', 'VANADIUM µg/l', '', '', '', '', 'VANADIUM µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G116', 'WASSERTEMPERATUR °C', '', '', '', '', 'WASSERTEMPERATUR °C', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G142', 'ZINK mg/l', '', '', 'Zn', 'MET', 'ZINK mg/l', 'G142', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G423', 'ZINK µg/l', '', '', 'Zn', 'MET', 'ZINK µg/l', 'G142', '$messwert / 1000.0');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G530', 'α-Hexachlorcyclohexan µg/l', '', '', '', '', 'α-Hexachlorcyclohexan µg/l', '', '');

INSERT INTO CSX_MAPPING_WAGW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('G531', 'β-Hexachlorcyclohexan µg/l', '', '', '', '', 'β-Hexachlorcyclohexan µg/l', '', '');

-- Daten aus Datei D:\work\udm2020\src\main\import\Schadstoffe\Schadstoffe WAGW.csv in Tabelle CSX_MAPPING_WAGW importieren . Aufgabe erfolgreich und an Arbeitsblatt gesendet.

