SELECT TAG.ID,
       TAG.KEY,
       TAG.NAME,
       TAG.DESCRIPTION,
       TAG.TAGGROUP AS TAGGROUPID,
       TAG.TAGGROUP_KEY AS TAGGROUPKEY
FROM TAG
INNER JOIN JT_WAGW_STT ON JT_WAGW_STT.TAG = TAG.ID
AND JT_WAGW_STT.WAGW_STATION = ?
ORDER BY TAG.TAGGROUP_KEY,
         TAG.KEY
