SELECT DISTINCT %CLASS_ID% AS class_id, WAGW_STATION.ID as id, WAGW_STATION.NAME as name 
FROM WAGW_STATION 
INNER JOIN WAGW_SAMPLE_VALUE ON WAGW_SAMPLE_VALUE.STATION = WAGW_STATION.ID
WHERE WAGW_STATION.ID IN (%OBJECT_IDS%) 
AND %MAX_SAMPLE_VALUE_CONDITION%
AND WAGW_SAMPLE_VALUE.MAX_DATE BETWEEN (TO_DATE('%MIN_DATE%', 'YYYYMMDD')-1) AND (TO_DATE('%MAX_DATE%', 'YYYYMMDD')+1)
GROUP BY WAGW_STATION.ID, WAGW_STATION.NAME