SET DEFINE OFF

CREATE TABLE UIMDI02.CSX_REFLIST
  (
    POLLUTANT_KEY         VARCHAR2 (64 BYTE) NOT NULL ,
    POLLUTANT_NAME        VARCHAR2 (256 BYTE) NOT NULL ,
    POLLUTANT_DESCRIPTION VARCHAR2 (1024 BYTE) NOT NULL ,
    POLLUTANTGROUP        VARCHAR2 (256 BYTE) NOT NULL ,
    POLLUTANTGROUP_KEY    VARCHAR2 (64 BYTE) NOT NULL
  );


CREATE INDEX UIMDI02.CSX_REFLIST__IDX ON UIMDI02.CSX_REFLIST
  (
    POLLUTANT_KEY ASC ,
    POLLUTANTGROUP_KEY ASC
  );
  

ALTER TABLE UIMDI02.CSX_REFLIST ADD CONSTRAINT CSX_REFLIST_PK PRIMARY KEY ( POLLUTANT_KEY ) ;


INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Calcium', 'Calcium (Ca)', 'Ca', 'Düngemittel', 'DNM');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Calciumcarbonat', 'Calciumcarbonat (CaCO3)', 'CaCO3', 'Düngemittel', 'DNM');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Kalium', 'Kalium (K)', 'K', 'Düngemittel', 'DNM');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Magnesium', 'Magnesium (Mg)', 'Mg', 'Düngemittel', 'DNM');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Natrium', 'Natrium (Na)', 'Na', 'Düngemittel', 'DNM');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Phosphor', 'Gesamtphosphor (P)', 'P', 'Düngemittel', 'DNM');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Schwefel', 'Schwefel (S)', 'S', 'Düngemittel', 'DNM');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Sonst. DNM', 'Sonstige nicht näher spezifizierte Düngemittel', 'DNMplus', 'Düngemittel', 'DNM');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Stickstoff', 'Gesamtstickstoff (N)', 'N', 'Düngemittel', 'DNM');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('PCDD+PCDF', 'PCDD & PCDF (Dioxine & Furane)', 'PCDDundPCDF', 'Dioxine und Furane', 'DXF');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Anthracen', 'Anthracen', 'Anthracen', 'Kohlenwasserstoffe', 'KWS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Benzol', 'Benzol', 'Benzol', 'Kohlenwasserstoffe', 'KWS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Naphthalin', 'Naphthalin', 'Naphthalin', 'Kohlenwasserstoffe', 'KWS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('PCP', 'Pentachlorphenol (PCP)', 'PCP', 'Kohlenwasserstoffe', 'KWS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Pentachlorbenzol', 'Pentachlorbenzol', 'PeCB', 'Kohlenwasserstoffe', 'KWS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('PER', 'Tetrachlorethen (PER)', 'PER', 'Kohlenwasserstoffe', 'KWS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Sonst. KWS', 'Sonstige nicht näher spezifizierte Kohlenwasserstoffe', 'KWSplus', 'Kohlenwasserstoffe', 'KWS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('TCB', 'Trichlorbenzole (TCB)', 'TCB', 'Kohlenwasserstoffe', 'KWS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('TCM', 'Tetrachlormethan (TCM)', 'TCM', 'Kohlenwasserstoffe', 'KWS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Tetrachlorethan', '1,1,2,2-Tetrachlorethan', 'Tetrachlorethan', 'Kohlenwasserstoffe', 'KWS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Trichlorethan', '1,1,1-Trichlorethan', 'Trichlorethan', 'Kohlenwasserstoffe', 'KWS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Trichlorethylen', 'Trichlorethylen', 'Trichlorethylen', 'Kohlenwasserstoffe', 'KWS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Trichlormethan', 'Trichlormethan', 'Trichlormethan', 'Kohlenwasserstoffe', 'KWS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Aluminium', 'Aluminium (Al)', 'Al', 'Metalle und Schwermetalle', 'MET');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Antimon', 'Antimon (Sb)', 'Sb', 'Metalle und Schwermetalle', 'MET');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Arsen', 'Arsen und Verbindungen (As)', 'As', 'Metalle und Schwermetalle', 'MET');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Blei', 'Blei und Verbindungen (Pb)', 'Pb', 'Metalle und Schwermetalle', 'MET');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Cadmium', 'Cadmium und Verbindungen (Cd)', 'Cd', 'Metalle und Schwermetalle', 'MET');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Chrom', 'Chrom und Verbindungen (Cr)', 'Cr', 'Metalle und Schwermetalle', 'MET');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Cobalt', 'Cobalt (Co)', 'Co', 'Metalle und Schwermetalle', 'MET');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Eisen', 'Eisen (Fe)', 'Fe', 'Metalle und Schwermetalle', 'MET');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Kupfer', 'Kupfer und Verbindungen (Cu)', 'Cu', 'Metalle und Schwermetalle', 'MET');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Mangan', 'Mangan (Mn)', 'Mn', 'Metalle und Schwermetalle', 'MET');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Molybdän', 'Molybdän (Mo)', 'Mo', 'Metalle und Schwermetalle', 'MET');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Nickel', 'Nickel und Verbindungen (Ni)', 'Ni', 'Metalle und Schwermetalle', 'MET');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Quecksilber', 'Quecksilber und Verbindungen (Hg)', 'Hg', 'Metalle und Schwermetalle', 'MET');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Sonst. MET', 'Sonstige nicht näher spezifizierte Metalle und Schwermetalle', 'METplus', 'Metalle und Schwermetalle', 'MET');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Vanadium', 'Vanadium (V)', 'V', 'Metalle und Schwermetalle', 'MET');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Zink', 'Zink und Verbindungen (Zn)', 'Zn', 'Metalle und Schwermetalle', 'MET');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Zinn', 'Zinn (Sn)', 'Sn', 'Metalle und Schwermetalle', 'MET');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('PCB', 'Polychlorierte Biphenyle (PCBs)', 'PCB', 'Polychlorierte Biphenyle ', 'PCB');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Alachlor', 'Alachlor', 'Alachlor', 'Pestizide', 'PEST');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Aldrin', 'Aldrin', 'Aldrin', 'Pestizide', 'PEST');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Atrazin', 'Atrazin', 'Atrazin', 'Pestizide', 'PEST');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Chloralkane', 'Chloralkane, C10-C13', 'Chloralkane', 'Pestizide', 'PEST');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Chlordan', 'Chlordan', 'Chlordan', 'Pestizide', 'PEST');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Chlordecon', 'Chlordecon', 'Chlordecon', 'Pestizide', 'PEST');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Chlorfenvinphos', 'Chlorfenvinphos', 'Chlorfenvinphos', 'Pestizide', 'PEST');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Chlorpyrifos', 'Chlorpyrifos', 'Chlorpyrifos', 'Pestizide', 'PEST');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('DDT', 'DDT', 'DDT', 'Pestizide', 'PEST');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Dieldrin', 'Dieldrin', 'Dieldrin', 'Pestizide', 'PEST');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Diuron', 'Diuron', 'Diuron', 'Pestizide', 'PEST');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('DCM', 'Dichlormethan (DCM)', 'DCM', 'Pestizide', 'PEST');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('EDC', '1,2-Dichlorethan (EDC)', 'EDC', 'Pestizide', 'PEST');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Endosulfan', 'Endosulfan', 'Endosulfan', 'Pestizide', 'PEST');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Endrin', 'Endrin', 'Endrin', 'Pestizide', 'PEST');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Halogenkohlenwasserstoffe ', 'Halogenierte organische Verbindungen (als AOX)', 'AOX', 'Pestizide', 'PEST');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('HCB', 'Hexachlorbenzol (HCB)', 'HCB', 'Pestizide', 'PEST');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('HCBD', 'Hexachlorbutadien (HCBD)', 'HCBD', 'Pestizide', 'PEST');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('HCH', '1,2,3,4,5,6-Hexachlorcyclohexan (HCH)', 'HCH', 'Pestizide', 'PEST');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Heptachlor', 'Heptachlor', 'Heptachlor', 'Pestizide', 'PEST');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Lindan', 'Lindan', 'Lindan', 'Pestizide', 'PEST');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Mirex', 'Mirex', 'Mirex', 'Pestizide', 'PEST');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('OZV', 'Zinnorganische Verbindungen (OZV)', 'OZV', 'Pestizide', 'PEST');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Simazin', 'Simazin', 'Simazin', 'Pestizide', 'PEST');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Sonst. PEST', 'Sonstige nicht näher spezifizierte Pestizide', 'PESTplus', 'Pestizide', 'PEST');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Toxaphen', 'Toxaphen', 'Toxaphen', 'Pestizide', 'PEST');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Asbest', 'Asbest', 'Asbest', 'Synthetische Organische Schadstoffe', 'SOSS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Benzolperylen', 'Benzo(g,h,i)perylen', 'Benzoperylen', 'Synthetische Organische Schadstoffe', 'SOSS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Chlor', 'Chlor und anorganische Verbindungen (als HCl)', 'Cl', 'Synthetische Organische Schadstoffe', 'SOSS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Chloride', 'Chloride (als Gesamt-Cl)', 'Clr', 'Synthetische Organische Schadstoffe', 'SOSS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Cyanide', 'Cyanide (als Gesamt-CN)', 'CN', 'Synthetische Organische Schadstoffe', 'SOSS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('DEHP', 'Di-(2-ethylhexyl)phthalat (DEHP)', 'DEHP', 'Synthetische Organische Schadstoffe', 'SOSS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Ethylbenzol', 'Ethylbenzol', 'Ethylbenzol', 'Synthetische Organische Schadstoffe', 'SOSS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Ethylenoxid', 'Ethylenoxid', 'Ethylenoxid', 'Synthetische Organische Schadstoffe', 'SOSS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Fluoranthen', 'Fluoranthen', 'Fluoranthen', 'Synthetische Organische Schadstoffe', 'SOSS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Fluoride', 'Fluoride (als Gesamt-F)', 'Fl', 'Synthetische Organische Schadstoffe', 'SOSS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('HCN', 'Cyanwasserstoff (HCN)', 'HCN', 'Synthetische Organische Schadstoffe', 'SOSS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Hexabrombiphenyl', 'Hexabrombiphenyl', 'Hexabrombiphenyl', 'Synthetische Organische Schadstoffe', 'SOSS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('HFCKW', 'Fluor und anorganische Verbindungen (als HF)', 'HF', 'Synthetische Organische Schadstoffe', 'SOSS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Isodrin', 'Isodrin', 'Isodrin', 'Synthetische Organische Schadstoffe', 'SOSS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Isoproturon', 'Isoproturon', 'Isoproturon', 'Synthetische Organische Schadstoffe', 'SOSS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('NNP/NPE', 'Nonylphenol und Nonylphenolethoxylate (NP/NPEs)', 'NPNPEs', 'Synthetische Organische Schadstoffe', 'SOSS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Octylphenole ', 'Octylphenole und Octylphenolethoxylate', 'Octylphenole ', 'Synthetische Organische Schadstoffe', 'SOSS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('PAK', 'polyzyklische aromatische Kohlenwasserstoffe (PAK)', 'PAK', 'Synthetische Organische Schadstoffe', 'SOSS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('PBDE', 'Bromierte Diphenylether (PBDE)', 'PBDE', 'Synthetische Organische Schadstoffe', 'SOSS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Phenole', 'Phenole (als Gesamt-C)', 'Phenole', 'Synthetische Organische Schadstoffe', 'SOSS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('PM10', 'Feinstaub (PM10)', 'PM10', 'Treibhausgase und Luftschadstoffe', 'THGundLSS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Sonst. SYSS', 'Sonstige nicht näher spezifizierte Synthetische Schadstoffe', 'SYSSplus', 'Synthetische Organische Schadstoffe', 'SOSS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Toluol', 'Toluol', 'Tuluol', 'Synthetische Organische Schadstoffe', 'SOSS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Tributylzinn', 'Tributylzinn und Verbindungen', 'TBT', 'Synthetische Organische Schadstoffe', 'SOSS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Trifluralin', 'Trifluralin', 'Trifluralin', 'Synthetische Organische Schadstoffe', 'SOSS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Triphenylzinn', 'Triphenylzinn und Verbindungen', 'TPT ', 'Synthetische Organische Schadstoffe', 'SOSS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Vinylchlorid', 'Vinylchlorid', 'Vinylchlorid', 'Synthetische Organische Schadstoffe', 'SOSS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Xylole', 'Xylole', 'Xylole', 'Synthetische Organische Schadstoffe', 'SOSS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Ammoniak', 'Ammoniak (NH3)', 'NH3', 'Treibhausgase und Luftschadstoffe', 'THGundLSS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Distickoxid', 'Distickoxid (N2O)', 'N2O', 'Treibhausgase und Luftschadstoffe', 'THGundLSS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('FCKW', 'Fluorchlorkohlenwasserstoffe (FCKWs)', 'FCKW', 'Treibhausgase und Luftschadstoffe', 'THGundLSS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Halone', 'Halone', 'Halone', 'Treibhausgase und Luftschadstoffe', 'THGundLSS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('HFCKW', 'Teilhalogenierte Fluorchlorkohlenwasserstoffe (HFCKW)', 'HFCKW', 'Treibhausgase und Luftschadstoffe', 'THGundLSS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('HFKW', 'Teilfluorierte Kohlenwasserstoffe (HFKWs)', 'HFKW', 'Treibhausgase und Luftschadstoffe', 'THGundLSS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Kohlendioxid', 'Kohlendioxid (CO2)', 'CO2', 'Treibhausgase und Luftschadstoffe', 'THGundLSS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Kohlenmonoxid', 'Kohlenmonoxid (CO)', 'CO1', 'Treibhausgase und Luftschadstoffe', 'THGundLSS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Methan', 'Methan (CH4)', 'CH4', 'Treibhausgase und Luftschadstoffe', 'THGundLSS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('NMVOC', 'flüchtige organische Verbindungen ohne Methan (NMVOC)', 'NMVOC', 'Treibhausgase und Luftschadstoffe', 'THGundLSS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('PFKWs', 'Perfluorierte Kohlenwasserstoffe (PFKWs)', 'PFKW', 'Treibhausgase und Luftschadstoffe', 'THGundLSS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Schwefelhexafluorid', 'Schwefelhexafluorid (SF6)', 'SF6', 'Treibhausgase und Luftschadstoffe', 'THGundLSS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Schwefeloxid', 'Schwefeloxide (SOx/SO2)', 'SOx', 'Treibhausgase und Luftschadstoffe', 'THGundLSS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Sonst. LSS', 'Sonstige nicht näher spezifizierte Luftschadstoffe', 'THGundLSSplus', 'Treibhausgase und Luftschadstoffe', 'THGundLSS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('Stickoxide', 'Stickoxide (NO/NO2)', 'NOx', 'Treibhausgase und Luftschadstoffe', 'THGundLSS');

INSERT INTO CSX_REFLIST (POLLUTANT_NAME, POLLUTANT_DESCRIPTION, POLLUTANT_KEY, POLLUTANTGROUP, POLLUTANTGROUP_KEY) 
VALUES ('TOC', 'Gesamter organischer Kohlenstoff (TOC) (als Gesamt-C oder CSB/3)', 'TOC', 'Gesamter organischer Kohlenstoff ', 'TOC');

COMMIT;