MERGE INTO TAGGROUP EXISTING_TAGGROUP USING
  (SELECT 'POLLUTANT' KEY, 'Schadstoffe' NAME, 'Gruppe der Schadstoffe' DESCRIPTION
    FROM DUAL) NEW_TAGGROUP ON (EXISTING_TAGGROUP.KEY = NEW_TAGGROUP.KEY) 
WHEN NOT matched THEN insert(KEY, NAME, DESCRIPTION)
VALUES(NEW_TAGGROUP.KEY,
       NEW_TAGGROUP.NAME, NEW_TAGGROUP.DESCRIPTION);

MERGE INTO TAGGROUP EXISTING_TAGGROUP USING
  (SELECT 'POLLUTANTGROUP' KEY, 'Schadstoffgruppen' NAME, 'Gruppe der Schadstoffgruppen' DESCRIPTION
    FROM DUAL) NEW_TAGGROUP ON (EXISTING_TAGGROUP.KEY = NEW_TAGGROUP.KEY) 
WHEN NOT matched THEN insert(KEY, NAME, DESCRIPTION)
VALUES(NEW_TAGGROUP.KEY,
       NEW_TAGGROUP.NAME, NEW_TAGGROUP.DESCRIPTION);