DELETE FROM GEOM WHERE ID IN (SELECT BORIS_SITE.GEOMETRY FROM BORIS_SITE);
DELETE FROM TAG WHERE ID IN (SELECT BORIS_SITE.LITERATURE FROM BORIS_SITE);
DELETE FROM TAG WHERE ID IN (SELECT BORIS_SITE.INSTITUTION FROM BORIS_SITE);
%PRE-TRUNCATE-STATEMENTS%
TRUNCATE TABLE JT_BORIS_SITE_SAMPLE_VALUE;
TRUNCATE TABLE JT_BORIS_SITE_TAG;
TRUNCATE TABLE BORIS_SITE;
TRUNCATE TABLE BORIS_SAMPLE_VALUE;
%POST-TRUNCATE-STATEMENTS%