CREATE TABLE CSX_MAPPING_EPRTR ( PARAMETER_PK VARCHAR2(32),
PARAMETER_NAME VARCHAR2(128) NOT NULL,
PARAMETER_GROUP_PK VARCHAR2(32),
PARAMETER_GROUP_NAME VARCHAR2(128),
POLLUTANT_KEY VARCHAR2(64),
POLLUTANTGROUP_KEY VARCHAR2(64),
DISPLAY_NAME VARCHAR2(256),
UNIT VARCHAR2(64),
AGGREGATION_PK VARCHAR2(32),
AGGREGATION_CONVERSION VARCHAR2(128));

CREATE INDEX CSX_MAPPING_ER_IDXV1 ON CSX_MAPPING_EPRTR 
  (
    PARAMETER_PK ASC
  );
  
CREATE INDEX CSX_MAPPING_ER_IDXV2 ON CSX_MAPPING_EPRTR 
  (
    AGGREGATION_PK ASC
  );
  
CREATE INDEX CSX_MAPPING_ER_IDXV3 ON CSX_MAPPING_EPRTR 
  (
    POLLUTANT_KEY ASC
  );
  
CREATE INDEX CSX_MAPPING_ER_IDXV4 ON CSX_MAPPING_EPRTR 
  (
    POLLUTANTGROUP_KEY ASC
  );
  
ALTER TABLE CSX_MAPPING_EPRTR ADD CONSTRAINT CSX_MAPPING_EPRTR_PK PRIMARY KEY ( PARAMETER_PK );

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('aqiyrmtaadgcmy', '1,1,1-Trichlorethan', '', '', 'Trichlorethan', 'KWS', '1,1,1-Trichlorethan', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('twi4fyhwzhmmdr', '1,1,2,2-Tetrachlorethan', '', '', 'Tetrachlorethan', 'KWS', '1,1,2,2-Tetrachlorethan', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('zsgi4kxn4kwjia', '1,2-Dichlorethan (EDC)', '', '', 'EDC', 'PEST', '1,2-Dichlorethan', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('dnhp3xz6bw4t77', '1,2,3,4,5,6-Hexachlorcyclohexan (HCH)', '', '', 'HCH', 'PEST', '1,2,3,4,5,6-Hexachlorcyclohexan', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('64fhtkjukeyhx4', 'Alachlor', '', '', 'Alachlor', 'PEST', 'Alachlor', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('qafmhxahbi8p3w', 'Aldrin', '', '', 'Aldrin', 'PEST', 'Aldrin', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('yidbi85iuww432', 'Ammoniak (NH3)', '', '', 'NH3', 'THGundLSS', 'Ammoniak', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('hujnxm26k6qr8n', 'Anthracen', '', '', 'Anthracen', 'KWS', 'Anthracen', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('vkej8wwntdamht', 'Arsen und Verbindungen (als As)', '', '', 'As', 'MET', 'Arsen und Verbindungen', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('9kmywb743sxfuh', 'Asbest', '', '', 'Asbest', 'SOSS', 'Asbest', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('9gfq79y52pdytp', 'Atrazin', '', '', 'Atrazin', 'PEST', 'Atrazin', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('mgn5vpaka45pih', 'Benzo(g,h,i)perylen', '', '', 'Benzoperylen', 'SOSS', 'Benzo(g,h,i)perylen', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('22jsmyrtcav2yf', 'Benzol', '', '', 'Benzol', 'KWS', 'Benzol', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('4qfaew6i56i24h', 'Blei und Verbindungen (als Pb)', '', '', 'Pb', 'MET', 'Blei und Verbindungen', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('j8jwcbgf3e5839', 'Bromierte Diphenylether (PBDE)', '', '', 'PBDE', 'SOSS', 'Bromierte Diphenylether', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('esepw9mbihitmm', 'Cadmium und Verbindungen (als Cd)', '', '', 'Cd', 'MET', 'Cadmium und Verbindungen', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('qemu7zhgcnr64q', 'Chlor und anorganische Verbindungen (als HCl)', '', '', 'Cl', 'SOSS', 'Chlor und anorganische Verbindungen', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('d8f7zktqw8btww', 'Chloralkane, C10-C13', '', '', 'Chloralkane', 'PEST', 'Chloralkane', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('snfuwkpsrtm6xh', 'Chlordan', '', '', 'Chlordan', 'PEST', 'Chlordan', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('bufykxefgxwc3b', 'Chlordecon', '', '', 'Chlordecon', 'PEST', 'Chlordecon', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('u2f4a943733ms4', 'Chlorfenvinphos', '', '', 'Chlorfenvinphos', 'PEST', 'Chlorfenvinphos', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('68mrhnstmihyyw', 'Chloride (als Gesamt-Cl)', '', '', 'Clr', 'SOSS', 'Chloride', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('xegbpxidncg4np', 'Chlorpyrifos', '', '', 'Chlorpyrifos', 'PEST', 'Chlorpyrifos', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('xyetmkbx9mp4de', 'Chrom und Verbindungen (als Cr)', '', '', 'Cr', 'MET', 'Chrom und Verbindungen', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('ssm4knwrsw7myb', 'Cyanide (als Gesamt-CN)', '', '', 'CN', 'SOSS', 'Cyanide', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('ecnfpn2pybvaxq', 'Cyanwasserstoff (HCN)', '', '', 'HCN', 'SOSS', 'Cyanwasserstoff', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('gkgfd982dgrash', 'DDT', '', '', 'DDT', 'PEST', 'DDT', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('cikp8ney5cntsu', 'Di-(2-ethylhexyl)phthalat (DEHP)', '', '', 'DEHP', 'SOSS', 'Di-(2-ethylhexyl)phthalat', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('iygnsxnbtq6rm4', 'Dichlormethan (DCM)', '', '', 'DCM', 'PEST', 'Dichlormethan', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('36gshacyivb2dv', 'Dieldrin', '', '', 'Dieldrin', 'PEST', 'Dieldrin', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('fcc7uwev5srtcc', 'Distickoxid (N2O)', '', '', 'N2O', 'THGundLSS', 'Distickoxid', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('mcgv7k3k9zj8hp', 'Diuron', '', '', 'Diuron', 'PEST', 'Diuron', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('6igzvxr9y5rh9d', 'Endosulfan', '', '', 'Endosulfan', 'PEST', 'Endosulfan', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('pqg5kagwp9zpda', 'Endrin', '', '', 'Endrin', 'PEST', 'Endrin', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('nkj5qyvrhpjpxu', 'Ethylbenzol', '', '', 'Ethylbenzol', 'SOSS', 'Ethylbenzol', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('7sj9fbkd8tqypm', 'Ethylenoxid', '', '', 'Ethylenoxid', 'SOSS', 'Ethylenoxid', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('xinjdzrcpf2jph', 'Feinstaub (PM10)', '', '', 'PM10', 'THGundLSS', 'Feinstaub', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('hqde9jt7j27a7u', 'flüchtige organische Verbindungen ohne Methan (NMVOC)', '', '', 'NMVOC', 'THGundLSS', 'flüchtige organische Verbindungen ohne Methan', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('u6nbzcb287k4tw', 'Fluor und anorganische Verbindungen (als HF)', '', '', 'HF', 'SOSS', 'Fluor und anorganische Verbindungen', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('zwnssn6m5qf2i4', 'Fluoranthen', '', '', 'Fluoranthen', 'SOSS', 'Fluoranthen', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('s8ect9hdc4u6m8', 'Fluorchlorkohlenwasserstoffe (FCKWs)', '', '', 'FCKW', 'THGundLSS', 'Fluorchlorkohlenwasserstoffe', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('bym8azmeh3ft35', 'Fluoride (als Gesamt-F)', '', '', 'Fl', 'SOSS', 'Fluoride', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('jnmeennvf5w8dm', 'Gesamter organischer Kohlenstoff (TOC) (als Gesamt-C oder CSB/3)', '', '', 'TOC', 'TOC', 'Gesamter organischer Kohlenstoff', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('qud5fj33wufpsm', 'Gesamtphosphor', '', '', 'P', 'DNM', 'Gesamtphosphor', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('7ndzq9de7p7hnt', 'Gesamtstickstoff', '', '', 'N', 'DNM', 'Gesamtstickstoff', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('8wg9ak7jfd6y4y', 'Halogenierte organische Verbindungen (als AOX)', '', '', 'AOX', 'PEST', 'Halogenierte organische Verbindungen', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('ceegij7z385cr2', 'Halone', '', '', 'Halone', 'THGundLSS', 'Halone', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('r4hcyxv76ie68s', 'Heptachlor', '', '', 'Heptachlor', 'PEST', 'Heptachlor', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('4anz7cjxjyvhep', 'Hexabrombiphenyl', '', '', 'Hexabrombiphenyl', 'SOSS', 'Hexabrombiphenyl', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('bahgpakuvnpccp', 'Hexachlorbenzol (HCB)', '', '', 'HCB', 'PEST', 'Hexachlorbenzol', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('ughkdmbhksum4d', 'Hexachlorbutadien (HCBD)', '', '', 'HCBD', 'PEST', 'Hexachlorbutadien', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('i4nwgzvauup8nw', 'Isodrin', '', '', 'Isodrin', 'SOSS', 'Isodrin', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('qykc5na2xxy6tf', 'Isoproturon', '', '', 'Isoproturon', 'SOSS', 'Isoproturon', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('cycyf8zkpiccgr', 'Kohlendioxid (CO2)', '', '', 'CO2', 'THGundLSS', 'Kohlendioxid', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('tscurwaxyd36cx', 'Kohlenmonoxid (CO)', '', '', 'CO1', 'THGundLSS', 'Kohlenmonoxid', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('g6exbw2kyryag8', 'Kupfer und Verbindungen (als Cu)', '', '', 'Cu', 'MET', 'Kupfer und Verbindungen', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('wuhtsaqs2294xy', 'Lindan', '', '', 'Lindan', 'PEST', 'Lindan', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('akcq3jka89wvk6', 'Methan (CH4)', '', '', 'CH4', 'THGundLSS', 'Methan', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('f2hxgmffr7ia3s', 'Mirex', '', '', 'Mirex', 'PEST', 'Mirex', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('96kgtyzpn36fi8', 'Naphthalin', '', '', 'Na', 'DNM', 'Naphthalin', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('jie6qkfwe2drct', 'Nickel und Verbindungen (als Ni)', '', '', 'Ni', 'MET', 'Nickel und Verbindungen', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('5ejz2m64sjbht2', 'Nonylphenol und Nonylphenolethoxylate (NP/NPEs)', '', '', 'NPNPEs', 'SOSS', 'Nonylphenol und Nonylphenolethoxylate', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('gqnn4cfzekartb', 'Octylphenole und Octylphenolethoxylate', '', '', 'Octylphenole ', 'SOSS', 'Octylphenole und Octylphenolethoxylate', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('y8h26x54hbpjtj', 'PCDD + PCDF (Dioxine + Furane) (als Teq)', '', '', 'PCDDundPCDF', 'DXF', 'Dioxine + Furane', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('ieh6vauq8fxrxd', 'Pentachlorbenzol', '', '', 'PeCB', 'KWS', 'Pentachlorbenzol', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('3kiajmjdxj42n6', 'Pentachlorphenol (PCP)', '', '', 'PCP', 'KWS', 'Pentachlorphenol', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('j4dnm89g2bkr3f', 'Perfluorierte Kohlenwasserstoffe (PFKWs)', '', '', 'PFKW', 'THGundLSS', 'Perfluorierte Kohlenwasserstoffe', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('vqktwy5mugt4im', 'Phenole (als Gesamt-C)', '', '', 'Phenole', 'SOSS', 'Phenole', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('ksid9x92nqc8sy', 'Polychlorierte Biphenyle (PCBs)', '', '', 'PCB', 'PCB', 'Polychlorierte Biphenyle', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('ewkxmbuajk4anf', 'polyzyklische aromatische Kohlenwasserstoffe (PAK)', '', '', 'PAK', 'SOSS', 'polyzyklische aromatische Kohlenwasserstoffe', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('2ce2z9q9pv5j8w', 'Quecksilber und Verbindungen (als Hg)', '', '', 'Hg', 'MET', 'Quecksilber und Verbindungen', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('5adscjx5rfr2s8', 'Schwefelhexafluorid (SF6)', '', '', 'SF6', 'THGundLSS', 'Schwefelhexafluorid', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('ngdv2wnsgjz8w2', 'Schwefeloxide (SOx/SO2)', '', '', 'SOx', 'THGundLSS', 'Schwefeloxide', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('5yihyaypduihir', 'Simazin', '', '', 'Simazin', 'PEST', 'Simazin', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('2wdixwiua7cjxm', 'Stickoxide (NO/NO2)', '', '', 'NOx', 'THGundLSS', 'Stickoxide', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('v6c36jp9enhm8f', 'Teilfluorierte Kohlenwasserstoffe (HFKWs)', '', '', 'HFKW', 'THGundLSS', 'Teilfluorierte Kohlenwasserstoffe', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('92d85wsqmykyie', 'Teilhalogenierte Fluorchlorkohlenwasserstoffe (HFCKW)', '', '', 'HFCKW', 'THGundLSS', 'Teilhalogenierte Fluorchlorkohlenwasserstoffe', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('n6imnmpb4yspnj', 'Tetrachlorethen (PER)', '', '', 'PER', 'KWS', 'Tetrachlorethen', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('8circydyt4xyec', 'Tetrachlormethan (TCM)', '', '', 'TCM', 'KWS', 'Tetrachlormethan', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('x4k3bnixaq9jd8', 'Toluol', '', '', 'Tuluol', 'SOSS', 'Toluol', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('fgjfiymu6wbac6', 'Toxaphen', '', '', 'Toxaphen', 'PEST', 'Toxaphen', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('hak6zy9jzvhrh2', 'Tributylzinn und Verbindungen', '', '', 'TBT', 'SOSS', 'Tributylzinn und Verbindungen', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('riiu3a4mi876h6', 'Trichlorbenzole (TCB) (alle Isomere)', '', '', 'TCB', 'KWS', 'Trichlorbenzole', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('c4i76a8jqmvthj', 'Trichlorethylen', '', '', 'Trichlorethylen', 'KWS', 'Trichlorethylen', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('wajbumw8fr2489', 'Trichlormethan', '', '', 'Trichlormethan', 'KWS', 'Trichlormethan', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('4umh4zdh694h5b', 'Trifluralin', '', '', 'Trifluralin', 'SOSS', 'Trifluralin', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('2gmaqbx8qzn29q', 'Triphenylzinn und Verbindungen', '', '', 'TPT ', 'SOSS', 'Triphenylzinn und Verbindungen', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('ynji9bchv2gj4u', 'Vinylchlorid', '', '', 'Vinylchlorid', 'SOSS', 'Vinylchlorid', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('m2mmtb36wecp85', 'Xylole', '', '', 'Xylole', 'SOSS', 'Xylole', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('mwfd49u7vas88b', 'Zink und Verbindungen (als Zn)', '', '', 'Zn', 'MET', 'Zink und Verbindungen', 'kg/Jahr', '', '');

INSERT INTO CSX_MAPPING_EPRTR (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('tckkibqcd8emn2', 'Zinnorganische Verbindungen (als Gesamt-Sn)', '', '', 'OZV', 'PEST', 'Zinnorganische Verbindungen', 'kg/Jahr', '', '');

-- Daten aus Datei D:\work\udm2020\src\main\import\Schadstoffe\Schadstoffe EPRTR.csv in Tabelle CSX_MAPPING_EPRTR importieren . Aufgabe erfolgreich und an Arbeitsblatt gesendet.
