BEGIN

MERGE INTO TAGGROUP EXISTING_TAGGROUP USING
  (SELECT 'EPRTR.NOTIFICATION_PERIOD' KEY, 'Meldeperiode' NAME, 'EPRTR Meldeperiode' DESCRIPTION
    FROM DUAL) NEW_TAGGROUP ON (EXISTING_TAGGROUP.KEY = NEW_TAGGROUP.KEY) 
WHEN NOT matched THEN insert(KEY, NAME, DESCRIPTION)
VALUES(NEW_TAGGROUP.KEY,
       NEW_TAGGROUP.NAME, NEW_TAGGROUP.DESCRIPTION);

MERGE INTO TAGGROUP EXISTING_TAGGROUP USING
  (SELECT 'EPRTR.RELEASE_TYPE' KEY, 'Freisetzungstyp' NAME, 'EPRTR Art der Freisetzung' DESCRIPTION
    FROM DUAL) NEW_TAGGROUP ON (EXISTING_TAGGROUP.KEY = NEW_TAGGROUP.KEY) 
WHEN NOT matched THEN insert(KEY, NAME, DESCRIPTION)
VALUES(NEW_TAGGROUP.KEY,
       NEW_TAGGROUP.NAME, NEW_TAGGROUP.DESCRIPTION);

MERGE INTO TAGGROUP EXISTING_TAGGROUP USING
  (SELECT 'k73nnukdrw9ipc' KEY, 'Wirtschaftszweige' NAME, 'Liste von Wirtschaftszweigen basierend auf der von Statistik Austria veröffentlichten ÖNACE 2008 Liste.' DESCRIPTION
    FROM DUAL) NEW_TAGGROUP ON (EXISTING_TAGGROUP.KEY = NEW_TAGGROUP.KEY) 
WHEN NOT matched THEN insert(KEY, NAME, DESCRIPTION)
VALUES(NEW_TAGGROUP.KEY,
       NEW_TAGGROUP.NAME, NEW_TAGGROUP.DESCRIPTION);

MERGE INTO TAGGROUP EXISTING_TAGGROUP USING
  (SELECT '6ear7vjaxz728j' KEY, 'Flussgebietseinheit-Planungsräume' NAME, 'Liste von österreichischen Flussgebietseinheit-Planungsräumen gemäß §55b Wasserrechtsgesetz 1959 idF BGBl. I Nr. 123/2006.' DESCRIPTION
    FROM DUAL) NEW_TAGGROUP ON (EXISTING_TAGGROUP.KEY = NEW_TAGGROUP.KEY) 
WHEN NOT matched THEN insert(KEY, NAME, DESCRIPTION)
VALUES(NEW_TAGGROUP.KEY,
       NEW_TAGGROUP.NAME, NEW_TAGGROUP.DESCRIPTION);

END;