--SET DEFINE OFF

CREATE TABLE CSX_MAPPING_BORIS ( PARAMETER_PK VARCHAR2(32),
PARAMETER_NAME VARCHAR2(128) NOT NULL,
PARAMETER_GROUP_PK VARCHAR2(32),
PARAMETER_GROUP_NAME VARCHAR2(128),
POLLUTANT_KEY VARCHAR2(64),
POLLUTANTGROUP_KEY VARCHAR2(64),
DISPLAY_NAME VARCHAR2(256),
AGGREGATION_PK VARCHAR2(32),
AGGREGATION_CONVERSION VARCHAR2(128));

CREATE INDEX CSX_MAPPING_BRS_IDXV1 ON CSX_MAPPING_BORIS 
  (
    PARAMETER_PK ASC
  );
  
CREATE INDEX CSX_MAPPING_BRS_IDXV2 ON CSX_MAPPING_BORIS 
  (
    AGGREGATION_PK ASC
  );
  
CREATE INDEX CSX_MAPPING_BRS_IDXV3 ON CSX_MAPPING_BORIS 
  (
    POLLUTANT_KEY ASC
  );
  
CREATE INDEX CSX_MAPPING_BRS_IDXV4 ON CSX_MAPPING_BORIS 
  (
    POLLUTANTGROUP_KEY ASC
  );
  

ALTER TABLE CSX_MAPPING_BORIS ADD CONSTRAINT CSX_MAPPING_BORIS_PK PRIMARY KEY ( PARAMETER_PK );

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('BCA3', 'Ca  (Gesamtgehalt) %', 'B10000', 'Allgemeine Bodenkennwerte und Nährstoffzustand', 'Ca', 'DNM', 'Ca  (Gesamtgehalt) [%]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('BCA1', 'Ca [mg/kg]', 'B10000', 'Allgemeine Bodenkennwerte und Nährstoffzustand', 'Ca', 'DNM', 'Ca [mg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('BCA2', 'Ca [mmol IÄ/kg]', 'B10000', 'Allgemeine Bodenkennwerte und Nährstoffzustand', 'Ca', 'DNM', 'Ca [mmol IÄ/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B100', 'CaCO3 %', 'B10000', 'Allgemeine Bodenkennwerte und Nährstoffzustand', 'CaCO3', 'DNM', 'CaCO3 [%]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('BCL1', 'Cl [mg/kg]', 'B10000', 'Allgemeine Bodenkennwerte und Nährstoffzustand', 'Cl', 'SOSS', 'Cl [mg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B108', 'DOC [mg/l]', 'B10000', 'Allgemeine Bodenkennwerte und Nährstoffzustand', '', '', 'DOC [mg/l]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B0F1', 'F [mg/kg]', 'B10000', 'Allgemeine Bodenkennwerte und Nährstoffzustand', '', '', 'F [mg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B0F2', 'Fluorid [mg/l]', 'B10000', 'Allgemeine Bodenkennwerte und Nährstoffzustand', 'Fl', 'SOSS', 'Fluorid [mg/l]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B0H2', 'H+ [mmol IÄ/kg]', 'B10000', 'Allgemeine Bodenkennwerte und Nährstoffzustand', '', '', 'H+ [mmol IÄ/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B104', 'Humus %', 'B10000', 'Allgemeine Bodenkennwerte und Nährstoffzustand', '', '', 'Humus [%]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B0K3', 'K (Gesamtgehalt)  %', 'B10000', 'Allgemeine Bodenkennwerte und Nährstoffzustand', 'K', 'DNM', 'K (Gesamtgehalt)  [%]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B0K1', 'K [mg/kg]', 'B10000', 'Allgemeine Bodenkennwerte und Nährstoffzustand', 'K', 'DNM', 'K [mg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B0K2', 'K [mmol IÄ/kg]', 'B10000', 'Allgemeine Bodenkennwerte und Nährstoffzustand', 'K', 'DNM', 'K [mmol IÄ/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B106', 'KAK berechnet Summe Einzelelemente [mmol IÄ/kg]', 'B10000', 'Allgemeine Bodenkennwerte und Nährstoffzustand', '', '', '', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('BMG3', 'Mg (Gesamtgehalt)  %', 'B10000', 'Allgemeine Bodenkennwerte und Nährstoffzustand', 'Mg', 'DNM', 'Mg (Gesamtgehalt)  [%]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('BMG1', 'Mg [mg/kg]', 'B10000', 'Allgemeine Bodenkennwerte und Nährstoffzustand', 'Mg', 'DNM', 'Mg [mg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('BMG2', 'Mg [mmol IÄ/kg]', 'B10000', 'Allgemeine Bodenkennwerte und Nährstoffzustand', 'Mg', 'DNM', 'Mg [mmol IÄ/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B0N3', 'N (Gesamtgehalt) %', 'B10000', 'Allgemeine Bodenkennwerte und Nährstoffzustand', 'N', 'DNM', 'N (Gesamtgehalt) [%]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('BNA1', 'Na [mg/kg]', 'B10000', 'Allgemeine Bodenkennwerte und Nährstoffzustand', 'Na', 'DNM', 'Na [mg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('BNA2', 'Na [mmol IÄ/kg]', 'B10000', 'Allgemeine Bodenkennwerte und Nährstoffzustand', 'Na', 'DNM', 'Na [mmol IÄ/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B0P1', 'P [mg/kg]', 'B10000', 'Allgemeine Bodenkennwerte und Nährstoffzustand', 'P', 'DNM', 'P [mg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B105', 'pH-Wert', 'B10000', 'Allgemeine Bodenkennwerte und Nährstoffzustand', '', '', '', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B0S3', 'S (Gesamtgehalt) %', 'B10000', 'Allgemeine Bodenkennwerte und Nährstoffzustand', '', '', '', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B107', 'SO4 -- [mg/kg]', 'B10000', 'Allgemeine Bodenkennwerte und Nährstoffzustand', '', '', '', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B102', 'TC %', 'B10000', 'Allgemeine Bodenkennwerte und Nährstoffzustand', '', '', '', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B103', 'TIC %', 'B10000', 'Allgemeine Bodenkennwerte und Nährstoffzustand', '', '', '', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B101', 'TOC %', 'B10000', 'Allgemeine Bodenkennwerte und Nährstoffzustand', '', '', '', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B432', 'H6CDD [ng/kg]', 'B40200', 'Dioxine und Furane (PCDD/F)', 'PCDDundPCDF', 'DXF', 'H6CDD [ng/kg]', 'B432', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B437', 'H6CDF [ng/kg]', 'B40200', 'Dioxine und Furane (PCDD/F)', 'PCDDundPCDF', 'DXF', 'H6CDF [ng/kg]', 'B437', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B433', 'H7CDD [ng/kg]', 'B40200', 'Dioxine und Furane (PCDD/F)', 'PCDDundPCDF', 'DXF', 'H7CDD [ng/kg]', 'B433', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B438', 'H7CDF [ng/kg]', 'B40200', 'Dioxine und Furane (PCDD/F)', 'PCDDundPCDF', 'DXF', 'H7CDF [ng/kg]', 'B438', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B434', 'O8CDD [ng/kg]', 'B40200', 'Dioxine und Furane (PCDD/F)', 'PCDDundPCDF', 'DXF', 'O8CDD [ng/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B439', 'O8CDF [ng/kg]', 'B40200', 'Dioxine und Furane (PCDD/F)', 'PCDDundPCDF', 'DXF', 'O8CDF [ng/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B431', 'P5CDD [ng/kg]', 'B40200', 'Dioxine und Furane (PCDD/F)', 'PCDDundPCDF', 'DXF', 'P5CDD [ng/kg]', 'B455', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B436', 'P5CDF [ng/kg]', 'B40200', 'Dioxine und Furane (PCDD/F)', 'PCDDundPCDF', 'DXF', 'P5CDF [ng/kg]', 'B456', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B455', 'Summe PCDD [ng/kg]', 'B40200', 'Dioxine und Furane (PCDD/F)', 'PCDDundPCDF', 'DXF', 'PCDD [ng/kg]', 'B455', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B456', 'Summe PCDF [ng/kg]', 'B40200', 'Dioxine und Furane (PCDD/F)', 'PCDDundPCDF', 'DXF', 'PCDF [ng/kg]', 'B456', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B458', 'TCDD-Äquivalente BGA [ng/kg]', 'B40200', 'Dioxine und Furane (PCDD/F)', 'PCDDundPCDF', 'DXF', 'TCDD-Äquivalente BGA [ng/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B459', 'TCDD-Äquivalente I-TEF [ng/kg]', 'B40200', 'Dioxine und Furane (PCDD/F)', 'PCDDundPCDF', 'DXF', 'TCDD-Äquivalente I-TEF [ng/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B430', 'T4CDD [ng/kg]', 'B40200', 'Dioxine und Furane (PCDD/F)', 'PCDDundPCDF', 'DXF', 'T4CDD [ng/kg]', 'B430', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B435', 'T4CDF[ng/kg]', 'B40200', 'Dioxine und Furane (PCDD/F)', 'PCDDundPCDF', 'DXF', 'T4CDF[ng/kg]', 'B435', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B445', '1,2,3,4,6,7,8-H7CDD [ng/kg]', 'B40200', 'Dioxine und Furane (PCDD/F)', 'PCDDundPCDF', 'DXF', '1,2,3,4,6,7,8-H7CDD [ng/kg]', 'B433', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B453', '1,2,3,4,6,7,8-H7CDF [ng/kg]', 'B40200', 'Dioxine und Furane (PCDD/F)', 'PCDDundPCDF', 'DXF', '1,2,3,4,6,7,8-H7CDF [ng/kg]', 'B438', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B442', '1,2,3,4,7,8-H6CDD [ng/kg]', 'B40200', 'Dioxine und Furane (PCDD/F)', 'PCDDundPCDF', 'DXF', '1,2,3,4,7,8-H6CDD [ng/kg]', 'B432', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B449', '1,2,3,4,7,8-H6CDF [ng/kg]', 'B40200', 'Dioxine und Furane (PCDD/F)', 'PCDDundPCDF', 'DXF', '1,2,3,4,7,8-H6CDF [ng/kg]', 'B437', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B454', '1,2,3,4,7,8,9-H7CDF [ng/kg]', 'B40200', 'Dioxine und Furane (PCDD/F)', 'PCDDundPCDF', 'DXF', '1,2,3,4,7,8,9-H7CDF [ng/kg]', 'B438', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B443', '1,2,3,6,7,8-H6CDD[ng/kg]', 'B40200', 'Dioxine und Furane (PCDD/F)', 'PCDDundPCDF', 'DXF', '1,2,3,6,7,8-H6CDD[ng/kg]', 'B432', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B450', '1,2,3,6,7,8-H6CDF [ng/kg]', 'B40200', 'Dioxine und Furane (PCDD/F)', 'PCDDundPCDF', 'DXF', '1,2,3,6,7,8-H6CDF [ng/kg]', 'B437', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B441', '1,2,3,7,8-P5CDD [ng/kg]', 'B40200', 'Dioxine und Furane (PCDD/F)', 'PCDDundPCDF', 'DXF', '1,2,3,7,8-P5CDD [ng/kg]', 'B455', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B447', '1,2,3,7,8-P5CDF [ng/kg]', 'B40200', 'Dioxine und Furane (PCDD/F)', 'PCDDundPCDF', 'DXF', '1,2,3,7,8-P5CDF [ng/kg]', 'B456', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B444', '1,2,3,7,8,9-H6CDD [ng/kg]', 'B40200', 'Dioxine und Furane (PCDD/F)', 'PCDDundPCDF', 'DXF', '1,2,3,7,8,9-H6CDD [ng/kg]', 'B432', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B451', '1,2,3,7,8,9-H6CDF [ng/kg]', 'B40200', 'Dioxine und Furane (PCDD/F)', 'PCDDundPCDF', 'DXF', '1,2,3,7,8,9-H6CDF [ng/kg]', 'B437', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B452', '2,3,4,6,7,8-H6CDF [ng/kg]', 'B40200', 'Dioxine und Furane (PCDD/F)', 'PCDDundPCDF', 'DXF', '2,3,4,6,7,8-H6CDF [ng/kg]', 'B437', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B448', '2,3,4,7,8-P5CDF [ng/kg]', 'B40200', 'Dioxine und Furane (PCDD/F)', 'PCDDundPCDF', 'DXF', '2,3,4,7,8-P5CDF [ng/kg]', 'B456', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B440', '2,3,7,8-T4CDD [ng/kg]', 'B40200', 'Dioxine und Furane (PCDD/F)', 'PCDDundPCDF', 'DXF', '2,3,7,8-T4CDD [ng/kg]', 'B430', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B446', '2,3,7,8-T4CDF [ng/kg]', 'B40200', 'Dioxine und Furane (PCDD/F)', 'PCDDundPCDF', 'DXF', '2,3,7,8-T4CDF [ng/kg]', 'B435', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('BAL1', 'Al [mg/kg]', 'B30000', 'Metalle, Schwermetalle', 'Al', 'MET', 'Al [mg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('BAL2', 'Al [mmol IÄ/kg]', 'B30000', 'Metalle, Schwermetalle', 'Al', 'MET', 'Al [mmol IÄ/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('BAS1', 'As [mg/kg]', 'B30000', 'Metalle, Schwermetalle', 'As', 'MET', 'As [mg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('BBA1', 'Ba [mg/kg]', 'B30000', 'Metalle, Schwermetalle', 'METplus', 'MET', 'Ba [mg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('BCD1', 'Cd [mg/kg]', 'B30000', 'Metalle, Schwermetalle', 'Cd', 'MET', 'Cd [mg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('BCO1', 'Co [mg/kg]', 'B30000', 'Metalle, Schwermetalle', 'Co', 'MET', 'Co [mg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('BCR1', 'Cr [mg/kg]', 'B30000', 'Metalle, Schwermetalle', 'Cr', 'MET', 'Cr [mg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('BCU1', 'Cu [mg/kg]', 'B30000', 'Metalle, Schwermetalle', 'Cu', 'MET', 'Cu [mg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('BFE1', 'Fe [mg/kg]', 'B30000', 'Metalle, Schwermetalle', 'Fe', 'MET', 'Fe [mg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('BFE2', 'Fe [mmol IÄ/kg]', 'B30000', 'Metalle, Schwermetalle', 'Fe', 'MET', 'Fe [mmol IÄ/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('BGA1', 'Ga [mg/kg]', 'B30000', 'Metalle, Schwermetalle', 'METplus', 'MET', 'Ga [mg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('BHG1', 'Hg [mg/kg]', 'B30000', 'Metalle, Schwermetalle', 'Hg', 'MET', 'Hg [mg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('BMN1', 'Mn [mg/kg]', 'B30000', 'Metalle, Schwermetalle', 'Mn', 'MET', 'Mn [mg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('BMN2', 'Mn [mmol IÄ/kg]', 'B30000', 'Metalle, Schwermetalle', 'Mn', 'MET', 'Mn [mmol IÄ/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('BMO1', 'Mo [mg/kg]', 'B30000', 'Metalle, Schwermetalle', 'Mo', 'MET', 'Mo [mg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('BNB1', 'Nb [mg/kg]', 'B30000', 'Metalle, Schwermetalle', 'METplus', 'MET', 'Nb [mg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('BNI1', 'Ni [mg/kg]', 'B30000', 'Metalle, Schwermetalle', 'Ni', 'MET', 'Ni [mg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('BPB1', 'Pb [mg/kg]', 'B30000', 'Metalle, Schwermetalle', 'Pb', 'MET', 'Pb [mg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('BPT1', 'Pt  (mg/kg)', 'B30000', 'Metalle, Schwermetalle', 'METplus', 'MET', 'Pt  (mg/kg)', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('BRB1', 'Rb [mg/kg]', 'B30000', 'Metalle, Schwermetalle', 'METplus', 'MET', 'Rb [mg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('BSB1', 'Sb [mg/kg]', 'B30000', 'Metalle, Schwermetalle', 'Sb', 'MET', 'Sb [mg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('BSE1', 'Se [mg/kg]', 'B30000', 'Metalle, Schwermetalle', 'METplus', 'MET', 'Se [mg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('BSN1', 'Sn [mg/kg]', 'B30000', 'Metalle, Schwermetalle', 'Sn', 'MET', 'Sn [mg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('BSR1', 'Sr [mg/kg]', 'B30000', 'Metalle, Schwermetalle', 'METplus', 'MET', 'Sr [mg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('BTE1', 'Te [mg/kg]', 'B30000', 'Metalle, Schwermetalle', 'METplus', 'MET', 'Te [mg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('BTH1', 'Th [mg/kg]', 'B30000', 'Metalle, Schwermetalle', 'METplus', 'MET', 'Th [mg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('BTI1', 'Ti [mg/kg]', 'B30000', 'Metalle, Schwermetalle', 'METplus', 'MET', 'Ti [mg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('BTL1', 'Tl [mg/kg]', 'B30000', 'Metalle, Schwermetalle', 'METplus', 'MET', 'Tl [mg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B0U1', 'U [mg/kg]', 'B30000', 'Metalle, Schwermetalle', 'METplus', 'MET', 'U [mg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B0V1', 'V [mg/kg]', 'B30000', 'Metalle, Schwermetalle', 'V', 'MET', 'V [mg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B0W1', 'W [mg/kg]', 'B30000', 'Metalle, Schwermetalle', 'METplus', 'MET', 'W [mg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B0Y1', 'Y [mg/kg]', 'B30000', 'Metalle, Schwermetalle', 'METplus', 'MET', 'Y [mg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('BYB1', 'Yb [mg/kg]', 'B30000', 'Metalle, Schwermetalle', 'METplus', 'MET', 'Yb [mg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('BZN1', 'Zn [mg/kg]', 'B30000', 'Metalle, Schwermetalle', 'Zn', 'MET', 'Zn [mg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('BZR1', 'Zr [mg/kg]', 'B30000', 'Metalle, Schwermetalle', 'METplus', 'MET', 'Zr [mg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B4C7', 'Alachlor [µg/kg]', 'B40500', 'N-hältige Herbizide und Fungizide', 'Alachlor', 'PEST', 'Alachlor [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B4C0', 'Atrazin [µg/kg]', 'B40500', 'N-hältige Herbizide und Fungizide', 'Atrazin', 'PEST', 'Atrazin [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B4C1', 'Desethylatrazin [µg/kg]', 'B40500', 'N-hältige Herbizide und Fungizide', 'PESTplus', 'PEST', 'Desethylatrazin [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B4D0', 'Metazachlor [µg/kg]', 'B40500', 'N-hältige Herbizide und Fungizide', 'PESTplus', 'PEST', 'Metazachlor [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B4D1', 'Metolachlor [µg/kg]', 'B40500', 'N-hältige Herbizide und Fungizide', 'PESTplus', 'PEST', 'Metolachlor [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B4D2', 'Prometryn [µg/kg]', 'B40500', 'N-hältige Herbizide und Fungizide', 'PESTplus', 'PEST', 'Prometryn [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B4D3', 'Propazin [µg/kg]', 'B40500', 'N-hältige Herbizide und Fungizide', 'PESTplus', 'PEST', 'Propazin [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B4C3', 'Simazin [µg/kg]', 'B40500', 'N-hältige Herbizide und Fungizide', 'Simazin', 'PEST', 'Simazin [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B4C5', 'Terbuthylazin [µg/kg]', 'B40500', 'N-hältige Herbizide und Fungizide', 'PESTplus', 'PEST', 'Terbuthylazin [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B4A3', 'Alpha-HCH [µg/kg]', 'B40400', 'Organochlorpestizide und verwandte Verbindungen', 'HCH', 'PEST', 'Alpha-HCH [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B4A4', 'Beta-HCH [µg/kg]', 'B40400', 'Organochlorpestizide und verwandte Verbindungen', 'HCH', 'PEST', 'Beta-HCH [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B481', 'Beta-Heptachlorepoxid [µg/kg]', 'B40400', 'Organochlorpestizide und verwandte Verbindungen', 'PESTplus', 'PEST', 'Beta-Heptachlorepoxid [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B490', 'DDD [µg/kg]', 'B40400', 'Organochlorpestizide und verwandte Verbindungen', 'PESTplus', 'PEST', 'DDD [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B489', 'DDE [µg/kg]', 'B40400', 'Organochlorpestizide und verwandte Verbindungen', 'PESTplus', 'PEST', 'DDE [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B486', 'DDT [µg/kg]', 'B40400', 'Organochlorpestizide und verwandte Verbindungen', 'DDT', 'PEST', 'DDT [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B4A6', 'Delta-HCH [µg/kg]', 'B40400', 'Organochlorpestizide und verwandte Verbindungen', 'HCH', 'PEST', 'Delta-HCH [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B496', 'Dichlorprop [µg/kg]', 'B40400', 'Organochlorpestizide und verwandte Verbindungen', 'PESTplus', 'PEST', 'Dichlorprop [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B493', 'Diclobutrazol [µg/kg]', 'B40400', 'Organochlorpestizide und verwandte Verbindungen', 'PESTplus', 'PEST', 'Diclobutrazol [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B484', 'Dieldrin [µg/kg]', 'B40400', 'Organochlorpestizide und verwandte Verbindungen', 'Dieldrin', 'PEST', 'Dieldrin [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B4A7', 'Epsilon-HCH [µg/kg]', 'B40400', 'Organochlorpestizide und verwandte Verbindungen', 'HCH', 'PEST', 'Epsilon-HCH [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B482', 'Gamma-Chlordan [µg/kg]', 'B40400', 'Organochlorpestizide und verwandte Verbindungen', 'Chlordan', 'PEST', 'Gamma-Chlordan [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B4A5', 'Gamma-HCH (Lindan) [µg/kg]', 'B40400', 'Organochlorpestizide und verwandte Verbindungen', 'Lindan', 'PEST', 'Gamma-HCH (Lindan) [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B480', 'Heptachlor [µg/kg]', 'B40400', 'Organochlorpestizide und verwandte Verbindungen', 'Heptachlor', 'PEST', 'Heptachlor [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B499', 'Hexachlorbenzol [µg/kg]', 'B40400', 'Organochlorpestizide und verwandte Verbindungen', 'HCB', 'PEST', 'Hexachlorbenzol [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B498', 'MCPA [µg/kg]', 'B40400', 'Organochlorpestizide und verwandte Verbindungen', 'PESTplus', 'PEST', 'MCPA [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B497', 'Mecoprop [µg/kg]', 'B40400', 'Organochlorpestizide und verwandte Verbindungen', 'PESTplus', 'PEST', 'Mecoprop [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B49A', 'op'' DDD [mg/kg]', 'B40400', 'Organochlorpestizide und verwandte Verbindungen', 'PESTplus', 'PEST', 'op'' DDD [mg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B48A', 'op'' DDE [µg/kg]', 'B40400', 'Organochlorpestizide und verwandte Verbindungen', 'PESTplus', 'PEST', 'op'' DDE [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B487', 'op'' DDT [µg/kg]', 'B40400', 'Organochlorpestizide und verwandte Verbindungen', 'DDT', 'PEST', 'op'' DDT [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B4A0', 'Pentachlorbenzol [µg/kg]', 'B40400', 'Organochlorpestizide und verwandte Verbindungen', 'PeCB', 'PEST', 'Pentachlorbenzol [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B4A2', 'Pentachlorphenol (PCP) [µg/kg]', 'B40400', 'Organochlorpestizide und verwandte Verbindungen', 'PCP', 'PEST', 'Pentachlorphenol (PCP) [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B49B', 'pp'' DDD [µg/kg]', 'B40400', 'Organochlorpestizide und verwandte Verbindungen', 'PESTplus', 'PEST', 'pp'' DDD [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B48B', 'pp'' DDE [µg/kg]', 'B40400', 'Organochlorpestizide und verwandte Verbindungen', 'PESTplus', 'PEST', 'pp'' DDE [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B488', 'pp'' DDT [µg/kg]', 'B40400', 'Organochlorpestizide und verwandte Verbindungen', 'DDT', 'PEST', 'pp'' DDT [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B492', 'Propiconazol [µg/kg]', 'B40400', 'Organochlorpestizide und verwandte Verbindungen', 'PESTplus', 'PEST', 'Propiconazol [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B479', 'Quintozen [µg/kg]', 'B40400', 'Organochlorpestizide und verwandte Verbindungen', 'PESTplus', 'PEST', 'Quintozen [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B4A8', 'Summe-HCH Isomere [µg/kg]', 'B40400', 'Organochlorpestizide und verwandte Verbindungen', 'HCH', 'PEST', 'Summe-HCH Isomere [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B4A1', 'Tetrachlorbenzol [µg/kg]', 'B40400', 'Organochlorpestizide und verwandte Verbindungen', 'PESTplus', 'PEST', 'Tetrachlorbenzol [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B494', 'Triadimefon [µg/kg]', 'B40400', 'Organochlorpestizide und verwandte Verbindungen', 'PESTplus', 'PEST', 'Triadimefon [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B495', '2,4-D [µg/kg]', 'B40400', 'Organochlorpestizide und verwandte Verbindungen', 'PESTplus', 'PEST', '2,4-D [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B462', 'PCB 101 [µg/kg]', 'B40300', 'Polychlorierte Biphenyle (PCB)', 'PCB', 'PCB', 'PCB 28-180 [µg/kg]', 'B462', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B467', 'PCB 126 [µg/kg]', 'B40300', 'Polychlorierte Biphenyle (PCB)', 'PCB', 'PCB', 'PCB 126 [µg/kg]', 'B462', '*1');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B463', 'PCB 138 [µg/kg]', 'B40300', 'Polychlorierte Biphenyle (PCB)', 'PCB', 'PCB', 'PCB 138 [µg/kg]', 'B462', '*1');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B464', 'PCB 153 [µg/kg]', 'B40300', 'Polychlorierte Biphenyle (PCB)', 'PCB', 'PCB', 'PCB 153 [µg/kg]', 'B462', '*1');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B468', 'PCB 169 [µg/kg]', 'B40300', 'Polychlorierte Biphenyle (PCB)', 'PCB', 'PCB', 'PCB 169 [µg/kg]', 'B462', '*1');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B465', 'PCB 180 [µg/kg]', 'B40300', 'Polychlorierte Biphenyle (PCB)', 'PCB', 'PCB', 'PCB 180 [µg/kg]', 'B462', '*1');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B460', 'PCB 28 [µg/kg]', 'B40300', 'Polychlorierte Biphenyle (PCB)', 'PCB', 'PCB', 'PCB 28 [µg/kg]', 'B462', '*1');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B461', 'PCB 52 [µg/kg]', 'B40300', 'Polychlorierte Biphenyle (PCB)', 'PCB', 'PCB', 'PCB 52 [µg/kg]', 'B462', '*1');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B466', 'PCB 77 [µg/kg]', 'B40300', 'Polychlorierte Biphenyle (PCB)', 'PCB', 'PCB', 'PCB 77 [µg/kg]', 'B462', '*1');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B46A', 'PCB 81 [µg/kg]', 'B40300', 'Polychlorierte Biphenyle (PCB)', 'PCB', 'PCB', 'PCB 81 [µg/kg]', 'B462', '*1');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B400', 'Acenaphthen [µg/kg]', 'B40100', 'Polyzyklische Aromatische Kohlenwasserstoffe (PAH)', 'KWSplus', 'KWS', 'Acenaphthen [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B401', 'Acenaphthylen [µg/kg]', 'B40100', 'Polyzyklische Aromatische Kohlenwasserstoffe (PAH)', 'KWSplus', 'KWS', 'Acenaphthylen [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B416', 'Antanthren [µg/kg]', 'B40100', 'Polyzyklische Aromatische Kohlenwasserstoffe (PAH)', 'KWSplus', 'KWS', 'Antanthren [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B402', 'Anthracen [µg/kg]', 'B40100', 'Polyzyklische Aromatische Kohlenwasserstoffe (PAH)', 'Anthracen', 'KWS', 'Anthracen [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B403', 'Benzo(a)anthracen [µg/kg]', 'B40100', 'Polyzyklische Aromatische Kohlenwasserstoffe (PAH)', 'Anthracen', 'KWS', 'Benzo(a)anthracen [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B407', 'Benzo(a)pyren [µg/kg]', 'B40100', 'Polyzyklische Aromatische Kohlenwasserstoffe (PAH)', 'KWSplus', 'KWS', 'Benzopyren [µg/kg]', 'B407', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B404', 'Benzo(b)fluoranthen [µg/kg]', 'B40100', 'Polyzyklische Aromatische Kohlenwasserstoffe (PAH)', 'KWSplus', 'KWS', 'Benzofluoranthen [µg/kg]', 'B404', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B424', 'Benzo(b,j,k)fluoranthen [µg/kg]', 'B40100', 'Polyzyklische Aromatische Kohlenwasserstoffe (PAH)', 'KWSplus', 'KWS', 'Benzo(b,j,k)fluoranthen [µg/kg]', 'B404', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B417', 'Benzo(b)naphto(2,1-d)thiophen [µg/kg]', 'B40100', 'Polyzyklische Aromatische Kohlenwasserstoffe (PAH)', 'KWSplus', 'KWS', 'Benzo(b)naphto(2,1-d)thiophen [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B418', 'Benzo(e)pyren [µg/kg]', 'B40100', 'Polyzyklische Aromatische Kohlenwasserstoffe (PAH)', 'KWSplus', 'KWS', 'Benzo(e)pyren [µg/kg]', 'B407', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B406', 'Benzo(g,h,i)perylen [µg/kg]', 'B40100', 'Polyzyklische Aromatische Kohlenwasserstoffe (PAH)', 'Benzoperylen', 'KWS', 'Benzo(g,h,i)perylen [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B405', 'Benzo(k)fluoranthen [µg/kg]', 'B40100', 'Polyzyklische Aromatische Kohlenwasserstoffe (PAH)', 'KWSplus', 'KWS', 'Benzo(k)fluoranthen [µg/kg]', 'B404', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B408', 'Chrysen [µg/kg]', 'B40100', 'Polyzyklische Aromatische Kohlenwasserstoffe (PAH)', 'KWSplus', 'KWS', 'Chrysen [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B423', 'Chrysen und Triphenylen [µg/kg]', 'B40100', 'Polyzyklische Aromatische Kohlenwasserstoffe (PAH)', 'KWSplus', 'KWS', 'Chrysen und Triphenylen [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B419', 'Coronen [µg/kg]', 'B40100', 'Polyzyklische Aromatische Kohlenwasserstoffe (PAH)', 'KWSplus', 'KWS', 'Coronen [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B420', 'Cyclopenta (c,d) pyren [µg/kg]', 'B40100', 'Polyzyklische Aromatische Kohlenwasserstoffe (PAH)', 'KWSplus', 'KWS', 'Cyclopenta (c,d) pyren [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B425', 'Dibenzo(ah,ac)anthracen [µg/kg]', 'B40100', 'Polyzyklische Aromatische Kohlenwasserstoffe (PAH)', 'KWSplus', 'KWS', 'Dibenzo(ah,ac)anthracen [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B409', 'Dibenzo(a,h)anthracen [µg/kg]', 'B40100', 'Polyzyklische Aromatische Kohlenwasserstoffe (PAH)', 'KWSplus', 'KWS', 'Dibenzo(a,h)anthracen [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B410', 'Fluoranthen [µg/kg]', 'B40100', 'Polyzyklische Aromatische Kohlenwasserstoffe (PAH)', 'Fluoranthen', 'KWS', 'Fluoranthen [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B411', 'Fluoren [µg/kg]', 'B40100', 'Polyzyklische Aromatische Kohlenwasserstoffe (PAH)', 'KWSplus', 'KWS', 'Fluoren [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B412', 'Indeno(1,2,3-c,d)pyren [µg/kg]', 'B40100', 'Polyzyklische Aromatische Kohlenwasserstoffe (PAH)', 'KWSplus', 'KWS', 'Indeno(1,2,3-c,d)pyren [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B413', 'Naphthalin [µg/kg]', 'B40100', 'Polyzyklische Aromatische Kohlenwasserstoffe (PAH)', 'KWSplus', 'KWS', 'Naphthalin [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B421', 'Perylen [µg/kg]', 'B40100', 'Polyzyklische Aromatische Kohlenwasserstoffe (PAH)', 'KWSplus', 'KWS', 'Perylen [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B414', 'Phenanthren [µg/kg]', 'B40100', 'Polyzyklische Aromatische Kohlenwasserstoffe (PAH)', 'Naphthalin', 'KWS', 'Phenanthren [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B415', 'Pyren [µg/kg]', 'B40100', 'Polyzyklische Aromatische Kohlenwasserstoffe (PAH)', 'KWSplus', 'KWS', 'Pyren [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B422', 'Triphenylen [µg/kg]', 'B40100', 'Polyzyklische Aromatische Kohlenwasserstoffe (PAH)', 'KWSplus', 'KWS', 'Triphenylen [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B4F1', 'EOX [mg Cl/kg TS]', 'B40600', 'Sonstige organische Schadstoffe', '', '', 'EOX [mg Cl/kg TS]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B4F0', 'Octachlorstyrol (OCS) [µg/kg]', 'B40600', 'Sonstige organische Schadstoffe', '', '', 'Octachlorstyrol (OCS) [µg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B0B1', 'B [mg/kg]', 'B70000', 'Weitere Elemente der Bodenanalyse', '', '', 'B [mg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('BBR1', 'Br [mg/kg]', 'B70000', 'Weitere Elemente der Bodenanalyse', '', '', 'Br [mg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('BCS2', 'Cs 134 [kBQ/m²] (bezogen auf 1. 5. 86)', 'B70000', 'Weitere Elemente der Bodenanalyse', '', '', 'Cs 134 [kBQ/m²] (bezogen auf 1. 5. 86)', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('BCS3', 'Cs 137 (Bombenanteil) [kBq/m²] (bez. 1.5. 1986)', 'B70000', 'Weitere Elemente der Bodenanalyse', '', '', 'Cs 137 (Bombenanteil) [kBq/m²] (bez. 1.5. 1986)', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('BCS1', 'Cs 137 [kBq/m²] (bezogen auf 1. 5. 1986)', 'B70000', 'Weitere Elemente der Bodenanalyse', '', '', 'Cs 137 [kBq/m²] (bezogen auf 1. 5. 1986)', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('BCS5', 'CS134 [kBq/kg]', 'B70000', 'Weitere Elemente der Bodenanalyse', '', '', 'CS134 [kBq/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('BCS4', 'CS137 [kBq/kg]', 'B70000', 'Weitere Elemente der Bodenanalyse', '', '', 'CS137 [kBq/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B0K4', 'K40 [kBq/kg]', 'B70000', 'Weitere Elemente der Bodenanalyse', '', '', 'K40 [kBq/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('BSI1', 'Si [mg/kg]', 'B70000', 'Weitere Elemente der Bodenanalyse', '', '', 'Si [mg/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('BTH2', 'Th 232[kBq/kg]', 'B70000', 'Weitere Elemente der Bodenanalyse', '', '', 'Th 232[kBq/kg]', '', '');

INSERT INTO CSX_MAPPING_BORIS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('B0U2', 'U238 [kBq/kg]', 'B70000', 'Weitere Elemente der Bodenanalyse', '', '', 'U238 [kBq/kg]', '', '');