CREATE TABLE CSX_MAPPING_WAGW ( PARAMETER_PK VARCHAR2(32),
PARAMETER_NAME VARCHAR2(128) NOT NULL,
PARAMETER_GROUP_PK VARCHAR2(32),
PARAMETER_GROUP_NAME VARCHAR2(128),
POLLUTANT_KEY VARCHAR2(64),
POLLUTANTGROUP_KEY VARCHAR2(64),
DISPLAY_NAME VARCHAR2(256),
AGGREGATION_PK VARCHAR2(32),
AGGREGATION_CONVERSION VARCHAR2(128));

CREATE INDEX CSX_MAPPING_BRS_IDXV1 ON CSX_MAPPING_WAGW 
  (
    PARAMETER_PK ASC
  );
  
CREATE INDEX CSX_MAPPING_BRS_IDXV2 ON CSX_MAPPING_WAGW 
  (
    AGGREGATION_PK ASC
  );
  
CREATE INDEX CSX_MAPPING_BRS_IDXV3 ON CSX_MAPPING_WAGW 
  (
    POLLUTANT_KEY ASC
  );
  
CREATE INDEX CSX_MAPPING_BRS_IDXV4 ON CSX_MAPPING_WAGW 
  (
    POLLUTANTGROUP_KEY ASC
  );
  

ALTER TABLE CSX_MAPPING_WAGW ADD CONSTRAINT CSX_MAPPING_WAGW_PK PRIMARY KEY ( PARAMETER_PK );
