CREATE TABLE CSX_MAPPING_WAOW ( PARAMETER_PK VARCHAR2(32),
PARAMETER_NAME VARCHAR2(128) NOT NULL,
PARAMETER_GROUP_PK VARCHAR2(32),
PARAMETER_GROUP_NAME VARCHAR2(128),
POLLUTANT_KEY VARCHAR2(64),
POLLUTANTGROUP_KEY VARCHAR2(64),
DISPLAY_NAME VARCHAR2(256),
AGGREGATION_PK VARCHAR2(32),
AGGREGATION_CONVERSION VARCHAR2(128));

CREATE INDEX CSX_MAPPING_GW_IDXV1 ON CSX_MAPPING_WAOW 
  (
    PARAMETER_PK ASC
  );
  
CREATE INDEX CSX_MAPPING_GW_IDXV2 ON CSX_MAPPING_WAOW 
  (
    AGGREGATION_PK ASC
  );
  
CREATE INDEX CSX_MAPPING_GW_IDXV3 ON CSX_MAPPING_WAOW 
  (
    POLLUTANT_KEY ASC
  );
  
CREATE INDEX CSX_MAPPING_GW_IDXV4 ON CSX_MAPPING_WAOW 
  (
    POLLUTANTGROUP_KEY ASC
  );
  
ALTER TABLE CSX_MAPPING_WAOW ADD CONSTRAINT CSX_MAPPING_WAOW_PK PRIMARY KEY ( PARAMETER_PK );

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F133', 'ABFILTRIERBARE STOFFE mg/l', '', '', '', '', 'ABFILTRIERBARE STOFFE mg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F240', 'ALACHLOR µg/l', '', '', 'Alachlor', 'PEST', 'ALACHLOR µg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F780', 'Alkalinität mmol/l', '', '', '', '', 'Alkalinität mmol/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F838', 'ALUMINIUM GEL. µg/l', '', '', 'Al', 'MET', 'ALUMINIUM GEL. µg/l', 'F160', '$messwert * 1000.0');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F160', 'ALUMINIUM GEL. mg/l', '', '', 'Al', 'MET', 'ALUMINIUM GEL. mg/l', 'F160', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F837', 'ALUMINIUM GES. µg/l', '', '', 'Al', 'MET', 'ALUMINIUM GES. µg/l', 'F837', '$messwert * 1000.0');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F159', 'ALUMINIUM GES. mg/l', '', '', 'Al', 'MET', 'ALUMINIUM GES. mg/l', 'F837', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F174', 'AMMONIAK-N mg/l', '', '', 'NH3', 'THGundLSS', 'AMMONIAK-N mg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F173', 'AMMONIUM-N mg/l', '', '', '', '', 'AMMONIUM-N mg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F677', 'ANTHRACEN µg/l', '', '', 'Anthracen', 'KWS', 'ANTHRACEN µg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F214', 'AOX (ber. als Cl) µg/l', '', '', '', '', 'AOX (ber. als Cl) µg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F846', 'ARSEN GEL. µg/l', '', '', 'As', 'MET', 'ARSEN GEL. µg/l', 'F168', '$messwert * 1000.0');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F168', 'ARSEN GEL. mg/l', '', '', 'As', 'MET', 'ARSEN GEL. mg/l', 'F168', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F845', 'ARSEN GES. µg/l', '', '', 'As', 'MET', 'ARSEN GES. µg/l', 'F167', '$messwert * 1000.0');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F167', 'ARSEN GES. mg/l', '', '', 'As', 'MET', 'ARSEN GES. mg/l', 'F167', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F234', 'ATRAZIN µg/l', '', '', 'Atrazin', 'PEST', 'ATRAZIN µg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F201', 'BENZO(A)PYREN µg/l', '', '', '', '', 'BENZO(A)PYREN µg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F203', 'BENZO(B)FLUORANTHEN µg/l', '', '', '', '', 'BENZO(B)FLUORANTHEN µg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F205', 'BENZO(G,H,I)PERYLEN µg/l', '', '', 'Benzoperylen', 'SOSS', 'BENZO(G,H,I)PERYLEN µg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F204', 'BENZO(K)FLUORANTHEN µg/l', '', '', '', '', 'BENZO(K)FLUORANTHEN µg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F733', 'BISPHENOL A µg/l', '', '', '', '', 'BISPHENOL A µg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F840', 'BLEI GEL. µg/l', '', '', 'Pb', 'MET', 'BLEI GEL. µg/l', 'F162', '$messwert * 1000.0');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F162', 'BLEI GEL. mg/l', '', '', 'Pb', 'MET', 'BLEI GEL. mg/l', 'F162', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F839', 'BLEI GES. µg/l', '', '', 'Pb', 'MET', 'BLEI GES. µg/l', 'F161', '$messwert * 1000.0');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F161', 'BLEI GES. mg/l', '', '', 'Pb', 'MET', 'BLEI GES. mg/l', 'F161', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F126', 'BSB5 OHNE NITRIF.H. mg/l', '', '', '', '', 'BSB5 OHNE NITRIF.H. mg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F830', 'CADMIUM GEL. µg/l', '', '', 'Cd', 'MET', 'CADMIUM GEL. µg/l', 'F152', '$messwert * 1000.0');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F152', 'CADMIUM GEL. mg/l', '', '', 'Cd', 'MET', 'CADMIUM GEL. mg/l', 'F152', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F829', 'CADMIUM GES. µg/l', '', '', 'Cd', 'MET', 'CADMIUM GES. µg/l', 'F151', '$messwert * 1000.0');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F151', 'CADMIUM GES. mg/l', '', '', 'Cd', 'MET', 'CADMIUM GES. mg/l', 'F151', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F143', 'CALCIUM mg/l', '', '', 'Cd', 'MET', 'CALCIUM mg/l', 'F151', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F187', 'C-H GES. (SUMME KW)(DIN38409 T18) mg/l', '', '', '', '', 'C-H GES. (SUMME KW)(DIN38409 T18) mg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F177', 'CHLORID (ber. als Cl) mg/l', '', '', 'Clr', 'SOSS', 'CHLORID (ber. als Cl) mg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F395', 'CHLOROPHYLL A µg/l', '', '', '', '', 'CHLOROPHYLL A µg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F548', 'Chlorophyll a [µg/l] - integrierte Gesamtprobe ', '', '', '', '', 'Chlorophyll a [µg/l] - integrierte Gesamtprobe ', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F699', 'CHLORPYRIFOS (CHLORPYRIFOS-ETHYL) µg/l', '', '', 'Chlorpyrifos', 'PEST', 'CHLORPYRIFOS (CHLORPYRIFOS-ETHYL) µg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F842', 'CHROM GEL. µg/l', '', '', 'Cr', 'MET', 'CHROM GEL. µg/l', 'F164', '$messwert * 1000.0');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F164', 'CHROM GEL. mg/l', '', '', 'Cr', 'MET', 'CHROM GEL. mg/l', 'F164', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F841', 'CHROM GES. µg/l', '', '', 'Cr', 'MET', 'CHROM GES. µg/l', 'F163', '$messwert * 1000.0');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F163', 'CHROM GES. mg/l', '', '', 'Cr', 'MET', 'CHROM GES. mg/l', 'F163', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F186', 'CYANID LEICHT FREIS. (ber. als CN) mg/l', '', '', 'CN', 'SOSS', 'CYANID mg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F851', 'der Entnahmetiefe entspr. Schichtvolumen [Mio m3]', '', '', '', '', 'der Entnahmetiefe entspr. Schichtvolumen [Mio m3]', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F235', 'DESETHYLATRAZIN µg/l', '', '', '', '', 'DESETHYLATRAZIN µg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F687', 'DIBUTYLZINN-KATION µg/l', '', '', '', '', 'DIBUTYLZINN-KATION µg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F753', 'Di-(2-ethylhexyl)phthalat (DEHP) µg/l', '', '', 'DEHP', 'SOSS', 'Di-(2-ethylhexyl)phthalat (DEHP) µg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F130', 'DOC (ber. als C) mg/l', '', '', '', '', 'DOC (ber. als C) mg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F273', 'EDTA mg/l', '', '', '', '', 'EDTA mg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F148', 'EISEN GEL. mg/l', '', '', 'Fe', 'MET', 'EISEN GEL. mg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F147', 'EISEN GES. mg/l', '', '', 'Fe', 'MET', 'EISEN GES. mg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F411', 'ELEKTR. LEITF. (bei 20°C) µS/cm', '', '', '', '', 'ELEKTR. LEITF. (bei 20°C) µS/cm', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F118', 'ELEKTR. LEITF. (bei 25°C) µS/cm', '', '', '', '', 'ELEKTR. LEITF. (bei 25°C) µS/cm', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F559', 'ENTNAHMETIEFE m', '', '', '', '', 'ENTNAHMETIEFE m', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F109', 'E-UHRZEIT SS.MM', '', '', '', '', 'E-UHRZEIT SS.MM', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F115', 'FAERBUNG', '', '', '', '', 'FAERBUNG', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F202', 'FLUORANTHEN µg/l', '', '', 'Fluoranthen', 'SOSS', 'FLUORANTHEN µg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F185', 'FLUORID (ber. als F) mg/l', '', '', 'Fl', 'SOSS', 'FLUORID (ber. als F) mg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F136', 'GESAMTHAERTE °dH', '', '', '', '', 'GESAMTHAERTE °dH', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F181', 'HYDROGENKARBONAT (ber. als HCO3) mg/l', '', '', '', '', 'HYDROGENKARBONAT (ber. als HCO3) mg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F206', 'INDENO(1,2,3-CD)PYREN µg/l', '', '', '', '', 'INDENO(1,2,3-CD)PYREN µg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F346', 'ISOPROPYLBENZOL mg/l', '', '', '', '', 'ISOPROPYLBENZOL mg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F146', 'KALIUM mg/l', '', '', 'K', 'DNM', 'KALIUM mg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F138', 'KARBONATHAERTE °dH', '', '', '', '', 'KARBONATHAERTE °dH', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F836', 'KUPFER GEL. µg/l', '', '', 'Cu', 'MET', 'KUPFER GEL. µg/l', 'F158', '$messwert * 1000.0');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F158', 'KUPFER GEL. mg/l', '', '', 'Cu', 'MET', 'KUPFER GEL. mg/l', 'F158', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F835', 'KUPFER GES. µg/l', '', '', 'Cu', 'MET', 'KUPFER GES. µg/l', 'F157', '$messwert * 1000.0');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F157', 'KUPFER GES. mg/l', '', '', 'Cu', 'MET', 'KUPFER GES. mg/l', 'F157', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F737', 'LAS µg/l', '', '', '', '', 'LAS µg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F190', 'LAS mg/l', '', '', '', '', 'LAS mg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F100', 'LFD. NUMMER', '', '', '', '', 'LFD. NUMMER', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F144', 'MAGNESIUM mg/l', '', '', 'Mg', 'DNM', 'MAGNESIUM mg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F150', 'MANGAN GEL. mg/l', '', '', 'Mn', 'MET', 'MANGAN GEL. mg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F149', 'MANGAN GES. mg/l', '', '', 'Mn', 'MET', 'MANGAN GES. mg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F678', 'NAPHTHALIN µg/l', '', '', 'Naphthalin', 'KWS', 'NAPHTHALIN µg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F145', 'NATRIUM mg/l', '', '', 'Na', 'DNM', 'NATRIUM mg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F844', 'NICKEL GEL. µg/l', '', '', 'Ni', 'MET', 'NICKEL GEL. µg/l', 'F166', '$messwert * 1000.0');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F166', 'NICKEL GEL. mg/l', '', '', 'Ni', 'MET', 'NICKEL GEL. mg/l', 'F166', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F843', 'NICKEL GES. µg/l', '', '', 'Ni', 'MET', 'NICKEL GES. µg/l', 'F165', '$messwert * 1000.0');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F165', 'NICKEL GES. mg/l', '', '', 'Ni', 'MET', 'NICKEL GES. mg/l', 'F165', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F176', 'NITRAT-N mg/l', '', '', '', '', 'NITRAT-N mg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F175', 'NITRIT-N mg/l', '', '', '', '', 'NITRIT-N mg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F272', 'NTA mg/l', '', '', '', '', 'NTA mg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F183', 'ORTHOPHOSPHAT-P mg/l', '', '', '', '', 'ORTHOPHOSPHAT-P mg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F198', 'PHENOLINDEX (ber. als Phenol) mg/l', '', '', '', '', 'PHENOLINDEX (ber. als Phenol) mg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F182', 'PHOSPHOR GES. (filtr.,ber. als P) mg/l', '', '', 'P', 'DNM', 'PHOSPHOR GES. (filtr.,ber. als P) mg/l', 'PHOSPHOR GES. mg/l', 'F182');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F271', 'PHOSPHOR GES. (unfiltr.,ber. als P) mg/l', '', '', 'P', 'DNM', 'PHOSPHOR GES. (unfiltr.,ber. als P) mg/l', '', 'F182');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F314', 'PHOSPHOR ORGAN.GEL. (ber. als P) mg/l', '', '', 'P', 'DNM', 'PHOSPHOR ORGAN.GEL. (ber. als P) mg/l', '', 'F182');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F315', 'PHOSPHOR PARTIKULÄR (ber. als P) mg/l', '', '', 'P', 'DNM', 'PHOSPHOR PARTIKULÄR (ber. als P) mg/l', '', 'F182');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F119', 'PH-WERT', '', '', '', '', 'PH-WERT', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F783', 'Phytoplankton Biovolumen mm³/l', '', '', '', '', 'Phytoplankton Biovolumen mm³/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F782', 'Phytoplankton Brettum-Index (4,00-2,00)', '', '', '', '', 'Phytoplankton Brettum-Index (4,00-2,00)', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F215', 'POX (ber. als Cl) µg/l', '', '', '', '', 'POX (ber. als Cl) µg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F832', 'QUECKSILBER GEL. µg/l', '', '', 'Hg', 'MET', 'QUECKSILBER GEL. µg/l', 'F154', '$messwert * 1000.0');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F154', 'QUECKSILBER GEL. mg/l', '', '', 'Hg', 'MET', 'QUECKSILBER GEL. mg/l', 'F154', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F831', 'QUECKSILBER GES. µg/l', '', '', 'Hg', 'MET', 'QUECKSILBER GES. µg/l', 'F153', '$messwert * 1000.0');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F153', 'QUECKSILBER GES. mg/l', '', '', 'Hg', 'MET', 'QUECKSILBER GES. mg/l', 'F153', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F124', 'SAUERSTOFFGEHALT mg/l', '', '', '', '', 'SAUERSTOFFGEHALT mg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F125', 'SAUERSTOFFSAETTIGUNG %', '', '', '', '', 'SAUERSTOFFSAETTIGUNG %', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F139', 'SBV 4,3 mmol/l', '', '', '', '', 'SBV 4,3 mmol/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F276', 'SEBUTHYLAZIN µg/l', '', '', '', '', 'SEBUTHYLAZIN µg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F449', 'SELEN gel. µg/l', '', '', 'METplus', 'MET', 'SELEN gel. µg/l', 'F435', '$messwert * 1000.0');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F435', 'SELEN GEL. mg/l', '', '', 'METplus', 'MET', 'SELEN GEL. mg/l', 'F435', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F450', 'SELEN ges. µg/l', '', '', 'METplus', 'MET', 'SELEN ges. µg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F558', 'SICHTTIEFE(Secchi 20cm) m', '', '', '', '', 'SICHTTIEFE(Secchi 20cm) m', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F738', 'SILBER GEL. µg/l', '', '', 'METplus', 'MET', 'SILBER GEL. µg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F350', 'SILBER GEL. mg/l', '', '', 'METplus', 'MET', 'SILBER GEL. mg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F237', 'SIMAZIN µg/l', '', '', 'Simazin', 'PEST', 'SIMAZIN µg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F178', 'SULFAT (ber. als SO4) mg/l', '', '', '', '', 'SULFAT (ber. als SO4) mg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F217', 'TETRACHLORETHEN µg/l', '', '', '', '', 'TETRACHLORETHEN µg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F131', 'TOC (ber. als C) mg/l', '', '', 'TOC', 'TOC', 'TOC (ber. als C) mg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F408', 'TRIBUTYLZINN-KATION µg/l', '', '', 'TBT', 'SOSS', 'TRIBUTYLZINN-KATION µg/l', 'F408', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F758', 'TRIBUTYLZINN-KATION ng/l', '', '', 'TBT', 'SOSS', 'TRIBUTYLZINN-KATION ng/l', 'F408', '$messwert * 1000.0');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F218', 'TRICHLORETHEN µg/l', '', '', '', '', 'TRICHLORETHEN µg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F434', 'TRICHLORMETHAN µg/l', '', '', 'Trichlormethan', 'KWS', 'TRICHLORMETHAN µg/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F760', 'TRIPHENYLZINN-KATION ng/l', '', '', 'TPT ', 'SOSS', 'TRIPHENYLZINN-KATION ng/l', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F117', 'WASSERTEMPERATUR °C', '', '', '', '', 'WASSERTEMPERATUR °C', '', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F834', 'ZINK GEL. µg/l', '', '', 'Zn', 'MET', 'ZINK GEL. µg/l', 'F156', '$messwert * 1000.0');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F156', 'ZINK GEL. mg/l', '', '', 'Zn', 'MET', 'ZINK GEL. mg/l', 'F156', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F833', 'ZINK GES. µg/l', '', '', 'Zn', 'MET', 'ZINK GES. µg/l', 'F155', '$messwert * 1000.0');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F155', 'ZINK GES. mg/l', '', '', 'Zn', 'MET', 'ZINK GES. mg/l', 'F155', '');

INSERT INTO CSX_MAPPING_WAOW (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('F675', '1,2,4-TRICHLORBENZOL µg/l', '', '', '', '', '1,2,4-TRICHLORBENZOL µg/l', '', '');

-- Daten aus Datei D:\work\udm2020\src\main\import\Schadstoffe\Schadstoffe WAOW.csv in Tabelle CSX_MAPPING_WAOW importieren . Aufgabe erfolgreich und an Arbeitsblatt gesendet.

