BEGIN

MERGE INTO TAGGROUP EXISTING_TAGGROUP USING
  (SELECT 'WAOW.ZUSTAENDIGE_STELLE' KEY, 'Zuständige Stelle' NAME, 'Zuständige Stelle' DESCRIPTION
    FROM DUAL) NEW_TAGGROUP ON (EXISTING_TAGGROUP.KEY = NEW_TAGGROUP.KEY) 
WHEN NOT matched THEN insert(KEY, NAME, DESCRIPTION)
VALUES(NEW_TAGGROUP.KEY,
       NEW_TAGGROUP.NAME, NEW_TAGGROUP.DESCRIPTION);

MERGE INTO TAGGROUP EXISTING_TAGGROUP USING
  (SELECT 'WAOW.GEWAESSER' KEY, 'Gewässer' NAME, 'Gewässer' DESCRIPTION
    FROM DUAL) NEW_TAGGROUP ON (EXISTING_TAGGROUP.KEY = NEW_TAGGROUP.KEY) 
WHEN NOT matched THEN insert(KEY, NAME, DESCRIPTION)
VALUES(NEW_TAGGROUP.KEY,
       NEW_TAGGROUP.NAME, NEW_TAGGROUP.DESCRIPTION);

END;