CREATE TABLE CSX_MAPPING_MOSS ( PARAMETER_PK VARCHAR2(32),
PARAMETER_NAME VARCHAR2(128) NOT NULL,
PARAMETER_GROUP_PK VARCHAR2(32),
PARAMETER_GROUP_NAME VARCHAR2(128),
POLLUTANT_KEY VARCHAR2(64),
POLLUTANTGROUP_KEY VARCHAR2(64),
DISPLAY_NAME VARCHAR2(256),
UNIT VARCHAR2(64),
AGGREGATION_PK VARCHAR2(32),
AGGREGATION_CONVERSION VARCHAR2(128));

CREATE INDEX CSX_MAPPING_MOSS_IDXV1 ON CSX_MAPPING_MOSS 
  (
    PARAMETER_PK ASC
  );
  
CREATE INDEX CSX_MAPPING_MOSS_IDXV2 ON CSX_MAPPING_MOSS 
  (
    AGGREGATION_PK ASC
  );
  
CREATE INDEX CSX_MAPPING_MOSS_IDXV3 ON CSX_MAPPING_MOSS 
  (
    POLLUTANT_KEY ASC
  );
  
CREATE INDEX CSX_MAPPING_MOSS_IDXV4 ON CSX_MAPPING_MOSS 
  (
    POLLUTANTGROUP_KEY ASC
  );
  

ALTER TABLE CSX_MAPPING_MOSS ADD CONSTRAINT CSX_MAPPING_MOSS_PK PRIMARY KEY ( PARAMETER_PK );


SET DEFINE OFF

INSERT INTO CSX_MAPPING_MOSS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('Al', 'Aluminium [mg/kg]', '', '', 'Al', 'MET', 'Aluminium', 'mg/kg', '', '');

INSERT INTO CSX_MAPPING_MOSS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('As', 'Arsen [mg/kg]', '', '', 'As', 'MET', 'Arsen', 'mg/kg', '', '');

INSERT INTO CSX_MAPPING_MOSS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('Cd', 'Cadmium [mg/kg]', '', '', 'Cd', 'MET', 'Cadmium', 'mg/kg', '', '');

INSERT INTO CSX_MAPPING_MOSS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('Co', 'Cobalt [mg/kg]', '', '', 'Co', 'MET', 'Cobalt', 'mg/kg', '', '');

INSERT INTO CSX_MAPPING_MOSS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('Cr', 'Chrom [mg/kg]', '', '', 'Cr', 'MET', 'Chrom', 'mg/kg', '', '');

INSERT INTO CSX_MAPPING_MOSS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('Cu', 'Kupfer [mg/kg]', '', '', 'Cu', 'MET', 'Kupfer', 'mg/kg', '', '');

INSERT INTO CSX_MAPPING_MOSS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('Fe', 'Eisen [mg/kg]', '', '', 'Fe', 'MET', 'Eisen', 'mg/kg', '', '');

INSERT INTO CSX_MAPPING_MOSS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('Mo', 'Molybdän [mg/kg]', '', '', 'Mo', 'MET', 'Molybdän', 'mg/kg', '', '');

INSERT INTO CSX_MAPPING_MOSS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('Ni', 'Nickel [mg/kg]', '', '', 'Ni', 'MET', 'Nickel', 'mg/kg', '', '');

INSERT INTO CSX_MAPPING_MOSS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('Pb', 'Blei [mg/kg]', '', '', 'Pb', 'MET', 'Blei', 'mg/kg', '', '');

INSERT INTO CSX_MAPPING_MOSS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('S', 'Schwefel [mg/kg]', '', '', 'S', 'DNM', 'Schwefel', 'mg/kg', '', '');

INSERT INTO CSX_MAPPING_MOSS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('V', 'Vanadium [mg/kg]', '', '', 'V', 'MET', 'Vanadium', 'mg/kg', '', '');

INSERT INTO CSX_MAPPING_MOSS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('Sb', 'Antimon [mg/kg]', '', '', 'Sb', 'MET', 'Antimon', 'mg/kg', '', '');

INSERT INTO CSX_MAPPING_MOSS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('Zn', 'Zink [mg/kg]', '', '', 'Zn', 'MET', 'Zink', 'mg/kg', '', '');

INSERT INTO CSX_MAPPING_MOSS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('Hg', 'Quecksilber [mg/kg]', '', '', 'Hg', 'MET', 'Quecksilber', 'mg/kg', '', '');

INSERT INTO CSX_MAPPING_MOSS (PARAMETER_PK, PARAMETER_NAME, PARAMETER_GROUP_PK, PARAMETER_GROUP_NAME, POLLUTANT_KEY, POLLUTANTGROUP_KEY, DISPLAY_NAME, UNIT, AGGREGATION_PK, AGGREGATION_CONVERSION) 
VALUES ('N', 'Gesamtstickstoff (Elementaranalyse) [mg/kg]', '', '', 'N', 'DNM', 'Gesamtstickstoff (Elementaranalyse)', 'mg/kg', '', '');

-- Daten aus Datei D:\work\udm2020\src\main\import\Schadstoffe\Schadstoffe MOOSE.csv in Tabelle CSX_MAPPING_MOSS importieren . Aufgabe erfolgreich und an Arbeitsblatt gesendet.
