BEGIN

MERGE INTO TAGGROUP EXISTING_TAGGROUP USING
  (SELECT 'MOSS.MOSS_TYPE' KEY, 'Moostyp' NAME, 'Moostyp' DESCRIPTION
    FROM DUAL) NEW_TAGGROUP ON (EXISTING_TAGGROUP.KEY = NEW_TAGGROUP.KEY) 
WHEN NOT matched THEN insert(KEY, NAME, DESCRIPTION)
VALUES(NEW_TAGGROUP.KEY,
       NEW_TAGGROUP.NAME, NEW_TAGGROUP.DESCRIPTION);

END;