CREATE OR REPLACE FORCE VIEW "UIM_DI01"."CSX_OBJECT_TAG" ("CLASS_ID", "OBJECT_ID", "TAG_ID", "MAX_DATE", "MIN_DATE") AS 
SELECT
  (SELECT ID
   FROM CS_CLASS
   WHERE lower(NAME) = 'moss') AS CLASS_ID,
       JT_MOSS_TAG.MOSS AS OBJECT_ID,
       JT_MOSS_TAG.TAG AS TAG_ID,
       MAX(MOSS_SAMPLE_VALUE.SAMPLE_DATE) AS MAX_DATE,
       MIN(MOSS_SAMPLE_VALUE.SAMPLE_DATE) AS MIN_DATE
FROM JT_MOSS_TAG
INNER JOIN MOSS_SAMPLE_VALUE ON MOSS_SAMPLE_VALUE.STATION = MOSS.ID
GROUP BY JT_MOSS_TAG.MOSS, JT_MOSS_TAG.TAG
UNION
SELECT
  (SELECT ID
   FROM CS_CLASS
   WHERE lower(NAME) = 'boris_site') AS CLASS_ID,
       JT_BORIS_SITE_TAG.BORIS_SITE AS OBJECT_ID,
       JT_BORIS_SITE_TAG.TAG AS TAG_ID,
       MAX(BORIS_SAMPLE_VALUE.MAX_DATE) AS MAX_DATE,
       MIN(BORIS_SAMPLE_VALUE.MAX_DATE) AS MIN_DATE
FROM JT_BORIS_SITE_TAG
INNER JOIN JT_BORIS_SSV ON JT_BORIS_SSV.BORIS_SITE = JT_BORIS_SITE_TAG.BORIS_SITE
INNER JOIN BORIS_SAMPLE_VALUE ON JT_BORIS_SSV.BORIS_SAMPLE_VALUE = BORIS_SAMPLE_VALUE.ID 
GROUP BY JT_BORIS_SITE_TAG.BORIS_SITE, JT_BORIS_SITE_TAG.TAG
UNION
SELECT
  (SELECT ID
   FROM CS_CLASS
   WHERE lower(NAME) = 'wagw_station') AS CLASS_ID,
       JT_WAGW_STT.WAGW_STATION AS OBJECT_ID,
       JT_WAGW_STT.TAG AS TAG_ID,
       MAX(WAGW_SAMPLE_VALUE.MAX_DATE) AS MAX_DATE,
       MIN(WAGW_SAMPLE_VALUE.MAX_DATE) AS MIN_DATE
FROM JT_WAGW_STT
INNER JOIN WAGW_SAMPLE_VALUE ON WAGW_SAMPLE_VALUE.STATION = JT_WAGW_STT.WAGW_STATION
GROUP BY JT_WAGW_STT.WAGW_STATION, JT_WAGW_STT.TAG
UNION
SELECT
  (SELECT ID
   FROM CS_CLASS
   WHERE lower(NAME) = 'waow_station') AS CLASS_ID,
       JT_WAOW_STT.WAOW_STATION AS OBJECT_ID,
       JT_WAOW_STT.TAG AS TAG_ID,
       MAX(WAOW_SAMPLE_VALUE.MAX_DATE) AS MAX_DATE,
       MIN(WAOW_SAMPLE_VALUE.MAX_DATE) AS MIN_DATE
FROM JT_WAOW_STT
INNER JOIN WAOW_SAMPLE_VALUE ON WAOW_SAMPLE_VALUE.STATION = JT_WAOW_STT.WAOW_STATION
GROUP BY JT_WAOW_STT.WAOW_STATION, JT_WAOW_STT.TAG
UNION
SELECT
  (SELECT ID
   FROM CS_CLASS
   WHERE lower(NAME) = 'eprtr_installation') AS CLASS_ID,
       JT_EPRTR_ITT.INSTALLATION AS OBJECT_ID,
       JT_EPRTR_ITT.TAG AS TAG_ID,
       MAX(EPRTR_RELEASE.MAX_DATE) AS MAX_DATE,
       MIN(EPRTR_RELEASE.MIN_DATE) AS MIN_DATE
FROM JT_EPRTR_ITT
INNER JOIN EPRTR_RELEASE ON EPRTR_RELEASE.INSTALLATION = JT_EPRTR_ITT.INSTALLATION
GROUP BY JT_EPRTR_ITT.INSTALLATION, JT_EPRTR_ITT.TAG