
CREATE OR REPLACE FORCE VIEW "UIM_DI01"."CSX_OBJECT_TAG" ("CLASS_ID", "OBJECT_ID", "TAG_ID") AS 
  SELECT
  (SELECT ID
   FROM CS_CLASS
   WHERE lower(NAME) = 'moss') AS CLASS_ID,
       MOSS AS OBJECT_ID,
       TAG AS TAG_ID
FROM JT_MOSS_TAG
UNION
SELECT
  (SELECT ID
   FROM CS_CLASS
   WHERE lower(NAME) = 'boris_site') AS CLASS_ID,
       BORIS_SITE AS OBJECT_ID,
       TAG AS TAG_ID
FROM JT_BORIS_SITE_TAG
UNION
SELECT
  (SELECT ID
   FROM CS_CLASS
   WHERE lower(NAME) = 'wagw_station') AS CLASS_ID,
       WAGW_STATION AS OBJECT_ID,
       TAG AS TAG_ID
FROM JT_WAGW_STT
UNION
SELECT
  (SELECT ID
   FROM CS_CLASS
   WHERE lower(NAME) = 'waow_station') AS CLASS_ID,
       WAOW_STATION AS OBJECT_ID,
       TAG AS TAG_ID
FROM JT_WAOW_STT
UNION
SELECT
  (SELECT ID
   FROM CS_CLASS
   WHERE lower(NAME) = 'eprtr_installation') AS CLASS_ID,
       INSTALLATION AS OBJECT_ID,
       TAG AS TAG_ID
FROM JT_EPRTR_ITT;
 
