SELECT TAG.ID,
       TAG.KEY,
       TAG.NAME,
       TAG.DESCRIPTION,
       TAG.TAGGROUP AS TAGGROUPID,
       TAG.TAGGROUP_KEY AS TAGGROUPKEY
FROM TAG
INNER JOIN JT_WAOW_STT ON JT_WAOW_STT.TAG = TAG.ID
AND JT_WAOW_STT.WAOW_STATION = ?
ORDER BY TAG.TAGGROUP_KEY,
         TAG.KEY
