SELECT DISTINCT %CLASS_ID% AS class_id, WAOW_STATION.ID as id, WAOW_STATION.NAME as name 
FROM WAOW_STATION 
INNER JOIN WAOW_SAMPLE_VALUE ON WAOW_SAMPLE_VALUE.STATION = WAOW_STATION.ID
WHERE WAOW_STATION.ID IN (%OBJECT_IDS%) 
AND %MAX_SAMPLE_VALUE_CONDITION%
AND WAOW_SAMPLE_VALUE.MAX_DATE BETWEEN (TO_DATE('%MIN_DATE%', 'YYYYMMDD')-1) AND (TO_DATE('%MAX_DATE%', 'YYYYMMDD')+1)
GROUP BY WAOW_STATION.ID, WAOW_STATION.NAME