INSERT INTO JT_WAOW_STT (WAOW_STATION, TAG) 
    SELECT DISTINCT :STATION_ID WAOW_STATION, POLLUTANT_GROUP TAG 
        FROM WAOW_SAMPLE_VALUE
        WHERE WAOW_SAMPLE_VALUE.STATION = :STATION_ID
        GROUP BY POLLUTANT_GROUP 
    UNION 
    SELECT DISTINCT :STATION_ID WAOW_STATION, POLLUTANT TAG 
        FROM WAOW_SAMPLE_VALUE
        WHERE WAOW_SAMPLE_VALUE.STATION = :STATION_ID
        GROUP BY POLLUTANT