INSERT INTO JT_WAOW_STT (WAOW_STATION, TAG) 
    SELECT DISTINCT :WAOW_STATION WAOW_STATION, POLLUTANT_GROUP TAG 
        FROM WAOW_SAMPLE_VALUE
        WHERE WAOW_SAMPLE_VALUE.STATION = :WAOW_STATION
        GROUP BY POLLUTANT_GROUP 
    UNION 
    SELECT DISTINCT :WAOW_STATION WAOW_STATION, POLLUTANT TAG 
        FROM WAOW_SAMPLE_VALUE
        WHERE WAOW_SAMPLE_VALUE.STATION = :WAOW_STATION
        GROUP BY POLLUTANT