ALTER SESSION SET ddl_lock_timeout=360;
DELETE FROM GEOM WHERE ID IN (SELECT WAOW_STATION.GEOMETRY FROM WAOW_STATION);
DELETE FROM TAG WHERE ID IN (SELECT DISTINCT WAOW_STATION.ZUSTAENDIGE_STELLE FROM WAOW_STATION);
DELETE FROM TAG WHERE ID IN (SELECT DISTINCT WAOW_STATION.GEWAESSER_NAME FROM WAOW_STATION);
TRUNCATE TABLE JT_WAOW_STT;
TRUNCATE TABLE WAOW_STATION;
TRUNCATE TABLE WAOW_SAMPLE_VALUE;