SELECT DISTINCT INSTALLATION_ERAS_ID, 
    MAX(INSTALLATION_NAME) AS INSTALLATION_NAME, 
    LONGITUDE,
    LATITUDE,
    RELEASE_ID, 
    RELEASE_TYPE,
    NOTIFICATION_PERIOD,
    START_DATE,
    END_DATE,
    %RELEASE_DECODE_STATEMENTS%
FROM (SELECT 
    NOTIFICATION_HEADER.NOTR_INSTALLATION AS INSTALLATION_ERAS_ID, 
    INSTALLATION.INST_DENOTATION AS INSTALLATION_NAME,
    COORDINATES.COORD_LONGITUDE AS LONGITUDE, 
    COORDINATES.COORD_LATITUDE AS LATITUDE,
    NOTIFICATION_PERIOD.PER_MNEMONIC AS NOTIFICATION_PERIOD,
    NOTIFICATION_PERIOD.PER_NOTIFICATION_PERIODE_BEGIN AS START_DATE,
    NOTIFICATION_PERIOD.PER_NOTIFICATION_PERIODE_END AS END_DATE,
    RELEASE.ID AS RELEASE_ID,
    RELEASE_TYPE.RELTYPE_MNEMONIC AS RELEASE_TYPE, 
    RELEASE.REL_QUANTITY_TOTAL_RELEASED AS QUANTITY_RELEASED, 
    RELEASE.REL_MEASUREMENT_METHOD AS MEASUREMENT_METHOD,
    RELEASE.REL_CALCULATION_METHOD AS CALCULATION_METHOD,
    RELEASE.REL_RELEASE_NEW AS POLLUTANT_KEY,
    ACTIVITY.ACT_ACTIVITY_CODE_NEW AS ACTIVITY_CODE,
    ACTIVITY.ACT_MNEMONIC AS ACTIVITY_MNEMONIC,
    ACTIVITY.ACT_DENOTATION AS ACTIVITY_NAME,
    ACTIVITY.ACT_IS_PRIMARY_PERF_ACTIVITY AS ACTIVITY_PRIMARY
FROM EDM_EPRTR_MASS.V_EPRTR_NOTIFICATION_HEADER NOTIFICATION_HEADER 
INNER JOIN EDM_EPRTR_MASS.V_EPRTR_INSTALLATION INSTALLATION
    ON INSTALLATION.INST_INSTALLATION = NOTIFICATION_HEADER.NOTR_INSTALLATION
INNER JOIN EDM_EPRTR_MASS.V_EPRTR_INST_COORDINATES COORDINATES 
    ON COORDINATES.COORD_NOTIFICATION_HEADER = NOTIFICATION_HEADER.ID
INNER JOIN EDM_EPRTR_MASS.V_EPRTR_RELEASE_ROOT RELEASE_ROOT
    ON RELEASE_ROOT.RELR_NOTIFICATION_HEADER = NOTIFICATION_HEADER.ID
INNER JOIN EDM_EPRTR_MASS.V_EPRTR_RELEASE RELEASE 
    ON RELEASE.REL_RELEASE_ROOT = RELEASE_ROOT.ID
INNER JOIN EDM_EPRTR_MASS.V_EPRTR_RELEASE_TYPE RELEASE_TYPE 
    ON RELEASE_TYPE.ID = RELEASE.REL_RELEASE_TYPE
INNER JOIN EDM_EPRTR_MASS.V_EPRTR_NOTIFICATION_PERIODE NOTIFICATION_PERIOD 
    ON NOTIFICATION_PERIOD.ID = NOTIFICATION_HEADER.NOTR_PERIOD
INNER JOIN EDM_EPRTR_MASS.V_EPRTR_RELEASE_ACTIVITY RELEASE_ACTIVITY
    ON RELEASE_ACTIVITY.RW_RELEASE_ROOT = RELEASE_ROOT.ID
INNER JOIN EDM_EPRTR_MASS.V_EPRTR_ACTIVITY_ROOT ACTIVITY_ROOT
    ON ACTIVITY_ROOT.ID = RELEASE_ACTIVITY.RW_ACTIVITY_ROOT
INNER JOIN EDM_EPRTR_MASS.V_EPRTR_ACTIVITY ACTIVITY 
    ON ACTIVITY.ACT_ACTIVITY_ROOT = ACTIVITY_ROOT.ID
WHERE NOTIFICATION_HEADER.NOTR_INSTALLATION IN (%INSTALLATION_ERAS_IDS%)
AND RELEASE.REL_RELEASE_NEW IN (%RELEASE_PARAMETER_PKS%)
ORDER BY INSTALLATION_ERAS_ID, NOTIFICATION_HEADER.ID, RELEASE.ID, ACTIVITY.ID)
GROUP BY 
    INSTALLATION_ERAS_ID, 
    LONGITUDE,
    LATITUDE,
    RELEASE_ID, 
    RELEASE_TYPE, 
    NOTIFICATION_PERIOD,
    START_DATE,
    END_DATE,
    QUANTITY_RELEASED, 
    POLLUTANT_KEY
ORDER BY 
    INSTALLATION_ERAS_ID,
    RELEASE_TYPE,
    NOTIFICATION_PERIOD