SELECT DISTINCT
          NOTIFICATION_HEADER.NOTR_INSTALLATION AS INSTALLATION_ERAS_ID,
          MAX(INSTALLATION.INST_DENOTATION) AS INSTALLATION_NAME,
          MAX(COORDINATES.COORD_LONGITUDE) AS LONGITUDE,
          MAX(COORDINATES.COORD_LATITUDE) AS LATITUDE,
          NOTIFICATION_PERIOD.PER_MNEMONIC AS NOTIFICATION_PERIOD,
          NOTIFICATION_PERIOD.PER_NOTIFICATION_PERIODE_BEGIN AS START_DATE,
          NOTIFICATION_PERIOD.PER_NOTIFICATION_PERIODE_END AS END_DATE,
          RELEASE_TYPE.RELTYPE_MNEMONIC AS RELEASE_TYPE,
          %RELEASE_DECODE_STATEMENTS%
   FROM EDM_EPRTR_MASS.V_EPRTR_NOTIFICATION_HEADER NOTIFICATION_HEADER
   INNER JOIN EDM_EPRTR_MASS.V_EPRTR_INSTALLATION INSTALLATION ON INSTALLATION.INST_INSTALLATION = NOTIFICATION_HEADER.NOTR_INSTALLATION
   INNER JOIN EDM_EPRTR_MASS.V_EPRTR_INST_COORDINATES COORDINATES ON COORDINATES.COORD_NOTIFICATION_HEADER = NOTIFICATION_HEADER.ID
   INNER JOIN EDM_EPRTR_MASS.V_EPRTR_RELEASE_ROOT RELEASE_ROOT ON RELEASE_ROOT.RELR_NOTIFICATION_HEADER = NOTIFICATION_HEADER.ID
   INNER JOIN EDM_EPRTR_MASS.V_EPRTR_RELEASE RELEASE ON RELEASE.REL_RELEASE_ROOT = RELEASE_ROOT.ID
   INNER JOIN EDM_EPRTR_MASS.V_EPRTR_RELEASE_TYPE RELEASE_TYPE ON RELEASE_TYPE.ID = RELEASE.REL_RELEASE_TYPE
   INNER JOIN EDM_EPRTR_MASS.V_EPRTR_NOTIFICATION_PERIODE NOTIFICATION_PERIOD ON NOTIFICATION_PERIOD.ID = NOTIFICATION_HEADER.NOTR_PERIOD
   WHERE NOTIFICATION_HEADER.NOTR_INSTALLATION IN (%INSTALLATION_ERAS_IDS%)
     AND RELEASE.REL_RELEASE_NEW IN (%RELEASE_PARAMETER_PKS%)
GROUP BY NOTIFICATION_HEADER.NOTR_INSTALLATION,
         RELEASE_TYPE.RELTYPE_MNEMONIC,
         NOTIFICATION_PERIOD.PER_MNEMONIC,
         NOTIFICATION_PERIOD.PER_NOTIFICATION_PERIODE_BEGIN,
         NOTIFICATION_PERIOD.PER_NOTIFICATION_PERIODE_END   
ORDER BY NOTIFICATION_HEADER.NOTR_INSTALLATION,
         RELEASE_TYPE.RELTYPE_MNEMONIC,
         NOTIFICATION_PERIOD.PER_MNEMONIC