SELECT MIN(AL_CONV) AS "MIN_AL",
       MAX(AL_CONV) AS "MAX_AL",
       MIN(AS_CONV) AS "MIN_AS",
       MAX(AS_CONV) AS "MAX_AS",
       MIN(CD_CONV) AS "MIN_CD",
       MAX(CD_CONV) AS "MAX_CD",
       MIN(CO_CONV) AS "MIN_CO",
       MAX(CO_CONV) AS "MAX_CO",
       MIN(CR_CONV) AS "MIN_CR",
       MAX(CR_CONV) AS "MAX_CR",
       MIN(CU_CONV) AS "MIN_CU",
       MAX(CU_CONV) AS "MAX_CU",
       MIN(FE_CONV) AS "MIN_FE",
       MAX(FE_CONV) AS "MAX_FE",
       MIN(MO_CONV) AS "MIN_MO",
       MAX(MO_CONV) AS "MAX_MO",
       MIN(NI_CONV) AS "MIN_NI",
       MAX(NI_CONV) AS "MAX_NI",
       MIN(PB_CONV) AS "MIN_PB",
       MAX(PB_CONV) AS "MAX_PB",
       MIN(S_CONV) AS "MIN_S",
       MAX(S_CONV) AS "MAX_S",
       MIN(V_CONV) AS "MIN_V",
       MAX(V_CONV) AS "MAX_V",
       MIN(SB_CONV) AS "MIN_SB",
       MAX(SB_CONV) AS "MAX_SB",
       MIN(ZN_CONV) AS "MIN_ZN",
       MAX(ZN_CONV) AS "MAX_ZN",
       MIN(HG_CONV) AS "MIN_HG",
       MAX(HG_CONV) AS "MAX_HG",
       MIN(N_TOTAL) AS "MIN_N",
       MAX(N_TOTAL) AS "MAX_N"
FROM MOSS
WHERE MOSS.ID IN (%OBJECT_IDS%)