SELECT DISTINCT %CLASS_ID% AS class_id,
                         MOSS.ID AS id,
                         MOSS.NAME AS name
FROM MOSS
INNER JOIN MOSS_SAMPLE_VALUE ON MOSS_SAMPLE_VALUE.STATION = MOSS.ID
WHERE MOSS.ID IN (%OBJECT_IDS%)
  AND %MAX_SAMPLE_VALUE_CONDITION%
  AND MOSS_SAMPLE_VALUE.SAMPLE_DATE BETWEEN (TO_DATE('%MIN_DATE%', 'YYYYMMDD')-1) AND (TO_DATE('%MAX_DATE%', 'YYYYMMDD')+1)
GROUP BY MOSS.ID,
         MOSS.NAME