INSERT INTO JT_WAGW_STT (WAGW_STATION, TAG) 
    SELECT DISTINCT :WAGW_STATION WAGW_STATION, POLLUTANT_GROUP TAG 
        FROM WAGW_SAMPLE_VALUE
        WHERE WAGW_SAMPLE_VALUE.STATION = :WAGW_STATION
        GROUP BY POLLUTANT_GROUP 
    UNION 
    SELECT DISTINCT :WAGW_STATION WAGW_STATION, POLLUTANT TAG 
        FROM WAGW_SAMPLE_VALUE
        WHERE WAGW_SAMPLE_VALUE.STATION = :WAGW_STATION
        GROUP BY POLLUTANT