INSERT INTO JT_WAGW_STT (WAGW_STATION, TAG) 
    SELECT DISTINCT :STATION_ID WAGW_STATION, POLLUTANT_GROUP TAG 
        FROM WAGW_SAMPLE_VALUE
        WHERE WAGW_SAMPLE_VALUE.STATION = :STATION_ID
        GROUP BY POLLUTANT_GROUP 
    UNION 
    SELECT DISTINCT :STATION_ID WAGW_STATION, POLLUTANT TAG 
        FROM WAGW_SAMPLE_VALUE
        WHERE WAGW_SAMPLE_VALUE.STATION = :STATION_ID
        GROUP BY POLLUTANT