INSERT INTO EPRTR_INSTALLATION (
    "KEY", 
    "NAME", 
    DESCRIPTION, 
    GEOMETRY, 
    NACE_CLASS, 
    RIVER_CATCHMENT, 
    --TAGS, 
    --RELEASES,
    SRC_ERAS_ID) 
VALUES( 
    :KEY,
    :NAME,
    :DESCRIPTION,
    :GEOMETRY, 
    (SELECT ID FROM TAG WHERE KEY = :NACE_CLASS AND TAGGROUP_KEY='k73nnukdrw9ipc'),  
    (SELECT ID FROM TAG WHERE KEY = :RIVER_CATCHMENT AND TAGGROUP_KEY='6ear7vjaxz728j'),  
    --(SELECT MAX(ID)+1 FROM EPRTR_INSTALLATION), 
    --(SELECT MAX(ID)+1 FROM EPRTR_INSTALLATION), 
    :SRC_ERAS_ID)
