INSERT INTO JT_EPRTR_STT (EPRTR_INSTALLATION, TAG) 
    SELECT DISTINCT :INSTALLATION_ID EPRTR_INSTALLATION, POLLUTANT_GROUP TAG 
        FROM EPRTR_RELEASE
        WHERE EPRTR_RELEASE.INSTALLATION = :INSTALLATION_ID
        GROUP BY POLLUTANT_GROUP 
    UNION 
    SELECT DISTINCT :INSTALLATION_ID EPRTR_INSTALLATION, POLLUTANT TAG 
        FROM EPRTR_RELEASE
        WHERE EPRTR_RELEASE.INSTALLATION = :INSTALLATION_ID
        GROUP BY POLLUTANT
    UNION 
    SELECT DISTINCT :INSTALLATION_ID EPRTR_INSTALLATION, NOTIFICATION_PERIOD TAG 
        FROM EPRTR_RELEASE
        WHERE EPRTR_RELEASE.INSTALLATION = :INSTALLATION_ID
        GROUP BY NOTIFICATION_PERIOD
    UNION 
    SELECT DISTINCT :INSTALLATION_ID EPRTR_INSTALLATION, RELEASE_TYPE TAG 
        FROM EPRTR_RELEASE
        WHERE EPRTR_RELEASE.INSTALLATION = :INSTALLATION_ID
        GROUP BY RELEASE_TYPE