SELECT RELEASE_ID, 
    RELEASE_TYPE,
    --INSTALLATION_ERAS_ID, 
    NOTIFICATION_PERIOD,
    START_DATE,
    END_DATE,
    QUANTITY_RELEASED, 
    --MEASUREMENT_METHOD,
    --CALCULATION_METHOD,
    POLLUTANT_KEY, 
    XMLSerialize(CONTENT XMLRoot(XMLELEMENT("ACTIVITIES",  
        xmlagg (xmlelement ("ACTIVITY", XMLATTRIBUTES(
                NOTIFICATION_PERIOD NOTIFICATIONPERIOD,
                ACTIVITY_CODE CODE,
                ACTIVITY_MNEMONIC MNEMONIC,
                ACTIVITY_NAME NAME,
                ACTIVITY_PRIMARY ISPRIMARY)))),VERSION '1.0', STANDALONE YES)) AS ACTIVITIES_XML
FROM
(SELECT NOTIFICATION_HEADER.NOTR_INSTALLATION AS INSTALLATION_ERAS_ID, 
    NOTIFICATION_PERIOD.PER_MNEMONIC AS NOTIFICATION_PERIOD,
    NOTIFICATION_PERIOD.PER_NOTIFICATION_PERIODE_BEGIN AS START_DATE,
    NOTIFICATION_PERIOD.PER_NOTIFICATION_PERIODE_END AS END_DATE,
    RELEASE.ID AS RELEASE_ID,
    RELEASE_TYPE.RELTYPE_MNEMONIC AS RELEASE_TYPE, 
    RELEASE.REL_QUANTITY_TOTAL_RELEASED AS QUANTITY_RELEASED, 
    RELEASE.REL_MEASUREMENT_METHOD AS MEASUREMENT_METHOD,
    RELEASE.REL_CALCULATION_METHOD AS CALCULATION_METHOD,
    RELEASE.REL_RELEASE_NEW AS POLLUTANT_KEY,
    ACTIVITY.ACT_ACTIVITY_CODE_NEW AS ACTIVITY_CODE,
    ACTIVITY.ACT_MNEMONIC AS ACTIVITY_MNEMONIC,
    ACTIVITY.ACT_DENOTATION AS ACTIVITY_NAME,
    ACTIVITY.ACT_IS_PRIMARY_PERF_ACTIVITY AS ACTIVITY_PRIMARY
    --ACTIVITY.ACT_PRODUCTION_VOLUME AS PRODUCTION_VOLUME
FROM EDM_EPRTR_MASS.V_EPRTR_NOTIFICATION_HEADER NOTIFICATION_HEADER 
INNER JOIN EDM_EPRTR_MASS.V_EPRTR_RELEASE_ROOT RELEASE_ROOT
    ON RELEASE_ROOT.RELR_NOTIFICATION_HEADER = NOTIFICATION_HEADER.ID
INNER JOIN EDM_EPRTR_MASS.V_EPRTR_RELEASE RELEASE 
    ON RELEASE.REL_RELEASE_ROOT = RELEASE_ROOT.ID
    --AND RELEASE.REL_RELEASE_TYPE = '3'
INNER JOIN EDM_EPRTR_MASS.V_EPRTR_RELEASE_TYPE RELEASE_TYPE 
    ON RELEASE_TYPE.ID = RELEASE.REL_RELEASE_TYPE
INNER JOIN EDM_EPRTR_MASS.V_EPRTR_NOTIFICATION_PERIODE NOTIFICATION_PERIOD 
    ON NOTIFICATION_PERIOD.ID = NOTIFICATION_HEADER.NOTR_PERIOD
INNER JOIN EDM_EPRTR_MASS.V_EPRTR_RELEASE_ACTIVITY RELEASE_ACTIVITY
    ON RELEASE_ACTIVITY.RW_RELEASE_ROOT = RELEASE_ROOT.ID
INNER JOIN EDM_EPRTR_MASS.V_EPRTR_ACTIVITY_ROOT ACTIVITY_ROOT
    ON ACTIVITY_ROOT.ID = RELEASE_ACTIVITY.RW_ACTIVITY_ROOT
INNER JOIN EDM_EPRTR_MASS.V_EPRTR_ACTIVITY ACTIVITY 
    ON ACTIVITY.ACT_ACTIVITY_ROOT = ACTIVITY_ROOT.ID
WHERE NOTIFICATION_HEADER.NOTR_INSTALLATION = :INSTALLATION_ERAS_ID
--WHERE ROWNUM < 1000
ORDER BY NOTIFICATION_HEADER.NOTR_INSTALLATION, NOTIFICATION_HEADER.ID, RELEASE.ID, ACTIVITY.ID)
GROUP BY 
    --INSTALLATION_ERAS_ID, 
    RELEASE_ID, 
    RELEASE_TYPE, 
    NOTIFICATION_PERIOD,
    START_DATE,
    END_DATE,
    QUANTITY_RELEASED, 
    --MEASUREMENT_METHOD,
    --CALCULATION_METHOD,
    POLLUTANT_KEY
    --HAVING COUNT(ACTIVITY_CODE) > 2