UPDATE EPRTR_INSTALLATION 
SET EPRTR_INSTALLATION.SRC_CONTENT = :SRC_CONTENT,
    EPRTR_INSTALLATION.SRC_CONTENT_CONFIDENTIAL = :SRC_CONTENT_CONFIDENTIAL
WHERE EPRTR_INSTALLATION.ID = :INSTALLATION_ID