UPDATE EPRTR_INSTALLATION 
SET EPRTR_INSTALLATION.SRC_CONTENT = ?,
    EPRTR_INSTALLATION.SRC_CONTENT_CONFIDENTIAL = ?,
    EPRTR_INSTALLATION.TAGS = ?,
    EPRTR_INSTALLATION.RELEASES = ?
WHERE EPRTR_INSTALLATION.ID = ?